GNSDK for Desktop: gracenote::metadata::GnRating Class Reference
gracenote::metadata::GnRating Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnRating ()
GnRating (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnRating ()
gnsdk_cstr_t Rating () const
gnsdk_cstr_t RatingBBFC () const
gnsdk_cstr_t RatingCanadianTV () const
gnsdk_cstr_t RatingCBFC () const
gnsdk_cstr_t RatingCHVRS () const
gnsdk_cstr_t RatingDesc () const
gnsdk_cstr_t RatingDJTCQ () const
gnsdk_cstr_t RatingDVDParental () const
gnsdk_cstr_t RatingEIRIN () const
gnsdk_cstr_t RatingFAB () const
gnsdk_cstr_t RatingFinnish () const
gnsdk_cstr_t RatingFrance () const
gnsdk_cstr_t RatingFSK () const
gnsdk_cstr_t RatingHongKong () const
gnsdk_cstr_t RatingINCAA () const
gnsdk_cstr_t RatingItaly () const
gnsdk_cstr_t RatingKMRB () const
gnsdk_cstr_t RatingMPAA () const
gnsdk_cstr_t RatingMPAATV () const
gnsdk_cstr_t RatingOFLC () const
gnsdk_cstr_t RatingQuebec () const
gnsdk_cstr_t RatingReason () const
gnsdk_cstr_t RatingSpain () const
gnsdk_cstr_t RatingType () const
gnsdk_uint32_t RatingTypeId () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnRating::GnRating () inline
gracenote::metadata::GnRating::GnRating (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnRating::~GnRating () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnRating::Rating () const inline
Rating value, e.g., PG
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingBBFC () const inline
A BBFC (British Board of Film Classification) rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingCanadianTV () const inline
A Canadian TV rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingCBFC () const inline
A CBFC (Central Board of Film Certification) rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingCHVRS () const inline
A CHVRS (Canadian Home Video Rating System) rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingDesc () const inline
Rating description .
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingDJTCQ () const inline
A DJTCQ (Dept of Justice, Rating, Titles and Qualification) (Brazil) rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingDVDParental () const inline
A DVD Parental rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingEIRIN () const inline
A EIRIN (Japan) rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingFAB () const inline
A FAB (Film Advisory Board) rating.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingFinnish () const inline
A Finnish rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingFrance () const inline
A French rating.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingFSK () const inline
A FSK (German) rating.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingHongKong () const inline
A Hong Kong rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingINCAA () const inline
A INCAA (Argentina) rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingItaly () const inline
An Italian rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingKMRB () const inline
A KMRB (Korea Media Rating Board) rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingMPAA () const inline
AMPAA (Motion Picture Assoc. of America) rating.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingMPAATV () const inline
A MPAA (Motion Picture Assoc. of America) TV rating type.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingOFLC () const inline
A OFLC (Australia) TV rating type value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingQuebec () const inline
A Quebecois rating.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingReason () const inline
Rating reason
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingSpain () const inline
A Spanish rating
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnRating::RatingType () const inline
Rating type value, e.g., MPAA .
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnRating::RatingTypeId () const inline
Rating type Id.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.