GNSDK for Desktop: gracenote::metadata::GnAudioWork Class Reference
gracenote::metadata::GnAudioWork Class Reference
Public Member Functions
GnAudioWork ()
GnAudioWork (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnAudioWork ()
gnsdk_cstr_t CompositionForm () const
GnCredit Credit () const
gnsdk_cstr_t Era (GnDataLevel level) const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnAudioWork, GNSDK_GDO_TYPE_AUDIO_WORK)
gnsdk_cstr_t GnUId () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_cstr_t ProductId () const
gnsdk_cstr_t TagId () const
GnTitle Title () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
A collection of classical music recordings.
Constructor & Destructor Documentation
gracenote::metadata::GnAudioWork::GnAudioWork () inline
Constructs empty GnAudioWork object
gracenote::metadata::GnAudioWork::GnAudioWork (gnsdk_gdo_handle_t gdoHandle) inline
Constructs a GnAudioWork object from a native handle
Parameters
gdoHandle [in] Native handle
virtual gracenote::metadata::GnAudioWork::~GnAudioWork () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnAudioWork::CompositionForm () const inline
Audio work's classical music composition form value (e.g., Symphony).
Returns
Compsition form
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::GnDataObject::StringValue().
GnCredit gracenote::metadata::GnAudioWork::Credit () const inline
Credit object for this audio work.
Returns
Credit
gnsdk_cstr_t gracenote::metadata::GnAudioWork::Era (GnDataLevel level) const inline
Audio work's era. List/locale dependent, multi-leveled field.
Parameters
level [in] Data level
Returns
Era
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::Genre (GnDataLevel level) const inline
Audio work's genre, e.g. punk rock, rock opera, etc. List/locale dependent, multi-level field.
Parameters
level [in] Data level
Returns
Genre
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::GnId () const inline
Audio work's Gracenote identifier
Returns
Gracenote identifier
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnAudioWork::GNSDK_CHECKED_CAST (GnAudioWork , GNSDK_GDO_TYPE_AUDIO_WORK)
gnsdk_cstr_t gracenote::metadata::GnAudioWork::GnUId () const inline
Audio work's Gracenote unique identifier.
Returns
Gracenote unique identifier
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::Origin (GnDataLevel level) const inline
Audio work's geographic location, e.g., New York City. List/locale dependent multi-leveled field.
Parameters
level [in] Data level
Returns
Origin
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::ProductId () const inline
Audio work's product ID (aka Tag ID).
Remarks:
Available for most types, this value can be stored or transmitted. Can be used as a static identifier for the current content as it will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::TagId () const inline
Gracenote Tag identifier for this audio work (Tag ID is same as Product ID)
Returns
Tag identifier
Remarks:
This method exists primarily to support legacy implementations. We recommend using the Product ID method to retrieve product related identifiers
References gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnAudioWork::Title () const inline
Audio work's official title.
Returns
Title
gnsdk_cstr_t gracenote::metadata::GnAudioWork::Tui () const inline
Gracenote Tui (title unique identifier) for this audio work.
Returns
Tui
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAudioWork::TuiTag () const inline
Gracenote Tui Tag for this audio work.
Returns
Tui Tag
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.