GNSDK for Desktop: gracenote::metadata::GnVideoCredit Class Reference
gracenote::metadata::GnVideoCredit Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnVideoCredit ()
GnVideoCredit (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnVideoCredit ()
gnsdk_cstr_t ArtistType (GnDataLevel level) const
gnsdk_cstr_t CharacterName () const
GnContributor Contributor () const
gnsdk_cstr_t Era (GnDataLevel level) const
gnsdk_cstr_t Genre (GnDataLevel level) const
GnName OfficialName () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_uint32_t Rank () const
gnsdk_cstr_t Role () const
gnsdk_cstr_t RoleBilling () const
gnsdk_uint32_t RoleId () const
season_iterable Seasons () const
series_iterable Series () const
works_iterable Works () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoCredit::GnVideoCredit () inline
gracenote::metadata::GnVideoCredit::GnVideoCredit (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnVideoCredit::~GnVideoCredit () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::ArtistType (GnDataLevel level) const inline
Artist type. This is a list/locale dependent, multi-level field
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
Parameters
level :enum value specifying level value
Returns
gnsdk_cstr_t
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::CharacterName () const inline
The character's name on the show.
References gracenote::metadata::GnDataObject::StringValue().
GnContributor gracenote::metadata::GnVideoCredit::Contributor () const inline
Contributor object.
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::Era (GnDataLevel level) const inline
Artist era. This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
Parameters
level [in] enum value specifying level value
Returns
gnsdk_cstr_t
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::Genre (GnDataLevel level) const inline
Genre, e.g., comedy. This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
Parameters
level :enum value specifying level value
Returns
gnsdk_cstr_t
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
GnName gracenote::metadata::GnVideoCredit::OfficialName () const inline
Official name object .
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::Origin (GnDataLevel level) const inline
Geographic location, e.g., "New York City". This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
Parameters
level [in] enum value specifying level value
Returns
gnsdk_cstr_t
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoCredit::Rank () const inline
Role's rank in importance.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::Role () const inline
Role, e.g., Actor.
Note:
For music credits, the absence of a role for a person indicates that person is the primary artist, who may have performed multiple roles.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoCredit::RoleBilling () const inline
A number identifying the role's listing in the credits.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoCredit::RoleId () const inline
Role ID
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
season_iterable gracenote::metadata::GnVideoCredit::Seasons () const inline
series_iterable gracenote::metadata::GnVideoCredit::Series () const inline
works_iterable gracenote::metadata::GnVideoCredit::Works () const inline
Iterable object that allows access to the collection of video work children.
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.