GNSDK for Desktop: gracenote::GnString Class Reference
gracenote::GnString Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnString ()
GnString (gnsdk_cstr_t str)
GnString (const GnString &str)
virtual ~GnString ()
const char * c_str () const
bool IsEmpty () const
operator gnsdk_cstr_t () const
GnString & operator= (const GnString &str)
GnString & operator= (gnsdk_cstr_t str)
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Static Public Member Functions
static GnString manage (gnsdk_cstr_t str)
Detailed Description
Managed immutable string as returned by GNSDK.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::GnString::GnString () inline
Construct an empty GnString object
Referenced by manage().
gracenote::GnString::GnString (gnsdk_cstr_t str) inline
Construct a GnString object from a native constant string
Parameters
str [in] Native string
gracenote::GnString::GnString (const GnString & str) inline
Construct a GnString object from an existing GnString object
Parameters
str [in] GnString object
virtual gracenote::GnString::~GnString () inline virtual
Member Function Documentation
const char* gracenote::GnString::c_str () const inline
Get native string
Returns
Native string
bool gracenote::GnString::IsEmpty () const inline
Get flag indicating if string object contains no string
Returns
True of empty, false otherwise
static GnString gracenote::GnString::manage (gnsdk_cstr_t str) inline static
Internally used factory for special SDK-managed strings
Parameters
str [in] Native string
Returns
Managed string
References GnString().
Referenced by gracenote::metadata::GnDataObject::Render(), and gracenote::metadata::GnDataObject::Serialize().
gracenote::GnString::operator gnsdk_cstr_t () const inline
GnString& gracenote::GnString::operator= (const GnString & str) inline
GnString& gracenote::GnString::operator= (gnsdk_cstr_t str) inline
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:49.