GNSDK for Desktop: gracenote::metadata::GnVideoProduct Class Reference
gracenote::metadata::GnVideoProduct Class Reference
Public Member Functions
GnVideoProduct ()
GnVideoProduct (gnsdk_gdo_handle_t gdoHandle)
GnVideoProduct (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnVideoProduct ()
gnsdk_cstr_t AspectRatio () const
gnsdk_cstr_t AspectRatioType () const
gnsdk_cstr_t CommerceType () const
content_iterable Contents () const
gnsdk_cstr_t DateOriginalRelease () const
gnsdk_cstr_t DateRelease () const
disc_iterable Discs () const
gnsdk_uint32_t Duration () const
gnsdk_cstr_t DurationUnits () const
externalid_iterable ExternalIds () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnVideoProduct, GNSDK_GDO_TYPE_VIDEO_PRODUCT)
gnsdk_cstr_t GnUId () const
bool IsFullResult () const
gnsdk_cstr_t Notes () const
GnTitle OfficialTitle () const
gnsdk_cstr_t PackageLanguage () const
gnsdk_cstr_t PackageLanguageDisplay () const
gnsdk_cstr_t ProductId () const
GnRating Rating () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
gnsdk_cstr_t VideoProductionType () const
gnsdk_uint32_t VideoProductionTypeId () const
gnsdk_cstr_t VideoRegion () const
gnsdk_cstr_t VideoRegionDesc () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
A Product refers to the commercial release of a Film, TV Series, or video content. Products contain a unique commercial code such as a UPC (Univeral Product Code), Hinban, or EAN (European Article Number). Products are for the most part released on a physical format, such as a DVD or Blu-ray.
Constructor & Destructor Documentation
gracenote::metadata::GnVideoProduct::GnVideoProduct () inline
gracenote::metadata::GnVideoProduct::GnVideoProduct (gnsdk_gdo_handle_t gdoHandle) inline
gracenote::metadata::GnVideoProduct::GnVideoProduct (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
virtual gracenote::metadata::GnVideoProduct::~GnVideoProduct () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::AspectRatio () const inline
Aspect ratio- describes the proportional relationship between the video's width and its height expressed as two numbers separated by a colon
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::AspectRatioType () const inline
Aspect ratio type, e.g., Standard
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::CommerceType () const inline
Commerce type value
Remarks:
For information on the specific values this key retrieves, contact your Gracenote Support Services representative.
References gracenote::metadata::GnDataObject::StringValue().
content_iterable gracenote::metadata::GnVideoProduct::Contents () const inline
Iterator for the content (cover art, biography, etc.) associated with this video work.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::DateOriginalRelease () const inline
Original release date in UTC format.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::DateRelease () const inline
Release date in UTC format
Remarks:
Release date values are not always available.
References gracenote::metadata::GnDataObject::StringValue().
disc_iterable gracenote::metadata::GnVideoProduct::Discs () const inline
Iterator for child video discs.
Remarks:
The ordinal parameter specifies the n'th child video disc to retrieve.
gnsdk_uint32_t gracenote::metadata::GnVideoProduct::Duration () const inline
Duration value in seconds, such as "3600" for a 60-minute program.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::DurationUnits () const inline
Duration units value (seconds, "SEC").
References gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnVideoProduct::ExternalIds () const inline
Iterator for external IDs. External IDs are 3rd party IDs used to cross link this metadata to 3rd party services, e.g. Amazon The ordinal parameter specifies the n'th child external ID to retrieve.
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::Genre (GnDataLevel level) const inline
Genre, e.g., Comedy. This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
This is a multi-level field requiring a GnDataLevel parameter
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::GnId () const inline
Gracenote ID
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoProduct::GNSDK_CHECKED_CAST (GnVideoProduct , GNSDK_GDO_TYPE_VIDEO_PRODUCT)
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::GnUId () const inline
Gracenote unique ID
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnVideoProduct::IsFullResult () const inline
Flag indicating if response result contains full (true) or partial metadata
Remarks:
Available for the following music and video types:
Album
Contributor
Track
Product
Season
Series
Work
Note:
What constitutes a full result varies among the individual response types and results, and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::Notes () const inline
Notes
References gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoProduct::OfficialTitle () const inline
Official child title object
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::PackageLanguage () const inline
Package language ISO code, e.g., "eng".
Remarks:
GNSDK supports a subset of the ISO 639-2 Language Code List. Specify a locale language's lower-case three-letter code, which is shown in the macro's C/C++ syntax section.
Note:
The following languages use Gracenote-specific three-letter codes:
qtb (Simplified Chinese)*
qtd (Traditional Chinese)*
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::PackageLanguageDisplay () const inline
Package display language, e.g., "English"
Remarks:
The language depends on availability - information in the language set for the locale may not be available, and the object's information may be available only in its default official language. For example, if a locale's set language is Spanish, but the object's information is available only in English, this value returns as English.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::ProductId () const inline
Product ID aka Tag ID
Remarks:
Available for most types, this value which can be stored or transmitted - it can bw used as a static identifier for the current content and will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
GnRating gracenote::metadata::GnVideoProduct::Rating () const inline
Rating object.
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::Tui () const inline
Tui (title-unique identifier)
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::TuiTag () const inline
Tui Tag value
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::VideoProductionType () const inline
Video production type value, e.g., Documentary
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoProduct::VideoProductionTypeId () const inline
Video production type identifier value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::VideoRegion () const inline
Video product region value, e.g, 1
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoProduct::VideoRegionDesc () const inline
Video product region description, e.g., USA, Canada, US Territories, Bermuda, and Cayman Islands
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.