GNSDK for Desktop: gracenote::metadata::GnVideoFeature Class Reference
gracenote::metadata::GnVideoFeature Class Reference
Public Member Functions
GnVideoFeature ()
GnVideoFeature (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnVideoFeature ()
gnsdk_cstr_t AspectRatio () const
gnsdk_cstr_t AspectRatioType () const
chapter_iterable Chapters () const
gnsdk_cstr_t DateOriginalRelease () const
gnsdk_cstr_t DateRelease () const
gnsdk_uint32_t Duration () const
gnsdk_cstr_t DurationUnits () const
gnsdk_cstr_t Genre (GnDataLevel level) const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnVideoFeature, GNSDK_GDO_TYPE_VIDEO_FEATURE)
bool Matched () const
gnsdk_cstr_t Notes () const
GnTitle OfficialTitle () const
gnsdk_uint32_t Ordinal () const
gnsdk_cstr_t PlotSummary () const
gnsdk_cstr_t PlotSynopsis () const
gnsdk_cstr_t PlotSynopsisLanguage () const
gnsdk_cstr_t PlotTagline () const
GnRating Rating () const
video_credit_iterable VideoCredits () const
gnsdk_cstr_t VideoFeatureType () const
gnsdk_cstr_t VideoProductionType () const
gnsdk_uint32_t VideoProductionTypeId () const
works_iterable Works ()
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Class containing metadata for a video feature, which has a full-length running time usually between 60 and 120 minutes. A feature is the main component of a DVD or Blu-ray disc which may, in addition, contain extra, or bonus, video clips and features.
Constructor & Destructor Documentation
gracenote::metadata::GnVideoFeature::GnVideoFeature () inline
gracenote::metadata::GnVideoFeature::GnVideoFeature (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnVideoFeature::~GnVideoFeature () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::AspectRatio () const inline
Aspect ratio - describes the proportional relationship between the video's width and its height expressed as two numbers separated by a colon
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::AspectRatioType () const inline
Aspect ratio type, e.g., Standard
References gracenote::metadata::GnDataObject::StringValue().
chapter_iterable gracenote::metadata::GnVideoFeature::Chapters () const inline
Iterator for child video chapters
Remarks:
The ordinal parameter specifies the n'th child video chapter to retrieve.
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::DateOriginalRelease () const inline
Original release date in UTC format.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::DateRelease () const inline
Release date in UTC format
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoFeature::Duration () const inline
Duration value in seconds.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::DurationUnits () const inline
Duration units value (e.g., seconds, "SEC")
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::Genre (GnDataLevel level) const inline
Genre. e.g., Drama. This is a list/locale dependent,multi-level field
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
This is a multi-level field requiring a GnDataLevel parameter
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoFeature::GNSDK_CHECKED_CAST (GnVideoFeature , GNSDK_GDO_TYPE_VIDEO_FEATURE)
bool gracenote::metadata::GnVideoFeature::Matched () const inline
Matched boolean value indicating whether this type is the one that matched the input criteria. Available from many video types.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::Notes () const inline
Notes
References gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoFeature::OfficialTitle () const inline
Official title object
gnsdk_uint32_t gracenote::metadata::GnVideoFeature::Ordinal () const inline
Feature's ordinal value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::PlotSummary () const inline
Plot summary
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::PlotSynopsis () const inline
Plot synopsis, e.g., (for Friends episode) "Monica's popularity at a karaoke club might have more to do with her revealing dress than her voice;
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::PlotSynopsisLanguage () const inline
Plot synopsis language, e.g., English
Remarks:
The language depends on availability - information in the language set for the locale may not be available, and the object's information may be available only in its default official language. For example, if a locale's set language is Spanish, but the object's information is available only in English, this value returns as English.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::PlotTagline () const inline
Plot tagline, e.g., "The terrifying motion picture from the terrifying No. 1 best seller." GNSDK_GDO_VALUE_PLOT_TAGLINE
References gracenote::metadata::GnDataObject::StringValue().
GnRating gracenote::metadata::GnVideoFeature::Rating () const inline
Rating object
video_credit_iterable gracenote::metadata::GnVideoFeature::VideoCredits () const inline
Iterable for child credits. For music types, this includes all credits except the artist credit.
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::VideoFeatureType () const inline
Video feature type value.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoFeature::VideoProductionType () const inline
Video production type value.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoFeature::VideoProductionTypeId () const inline
Video production ID type value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
works_iterable gracenote::metadata::GnVideoFeature::Works () inline
Iterator for child video works
Remarks:
The ordinal parameter specifies the n'th child video Work to retrieve.
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.