GNSDK for Desktop: gracenote::metadata::GnTrack Class Reference
gracenote::metadata::GnTrack Class Reference
Public Member Functions
GnTrack ()
GnTrack (gnsdk_gdo_handle_t gdoHandle)
GnTrack (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnTrack ()
GnArtist Artist () const
GnContent Content (GnContentType contentType) const
content_iterable Contents () const
credit_iterable Credits () const
gnsdk_uint32_t CurrentPosition () const
gnsdk_uint32_t Duration () const
externalid_iterable ExternalIds () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnTrack, GNSDK_GDO_TYPE_TRACK)
gnsdk_cstr_t GnUId () const
bool IsFullResult () const
gnsdk_cstr_t MatchConfidence () const
gnsdk_uint32_t MatchDuration () const
bool Matched () const
string_iterable MatchedIdents () const
gnsdk_cstr_t MatchLookupType () const
gnsdk_uint32_t MatchPosition () const
gnsdk_uint32_t MatchScore () const
gnsdk_cstr_t Mood (GnDataLevel level) const
GnContent Review () const
gnsdk_cstr_t TagId () const
gnsdk_cstr_t Tempo (GnDataLevel level) const
GnTitle Title () const
GnTitle TitleClassical () const
GnTitle TitleRegional () const
gnsdk_cstr_t TrackNumber () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
GnAudioWork Work () const
gnsdk_cstr_t Year () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
A song or instrumental recording.
Constructor & Destructor Documentation
gracenote::metadata::GnTrack::GnTrack () inline
Constructs empty GnTrack object
gracenote::metadata::GnTrack::GnTrack (gnsdk_gdo_handle_t gdoHandle) inline
Constructs a GnTrack object from a native handle
Parameters
gdoHandle [in] Native handle
gracenote::metadata::GnTrack::GnTrack (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
Constructs a GnTrack object from identifier and identifie tag
Parameters
id [in] Identifier
idTag [in] Identifier tag
virtual gracenote::metadata::GnTrack::~GnTrack () inline virtual
Member Function Documentation
GnArtist gracenote::metadata::GnTrack::Artist () const inline
Track's artist.
Returns
Artist
GnContent gracenote::metadata::GnTrack::Content (GnContentType contentType) const inline
Track's content, e.g., cover image, artist image, biography etc.
Parameters
GnContentType object
Returns
Content object
References gracenote::gnconvert::_convertContentTypeCppC().
content_iterable gracenote::metadata::GnTrack::Contents () const inline
Iterator for the content (cover art, biography, etc.) associated with this track.
Returns
Iterator
credit_iterable gracenote::metadata::GnTrack::Credits () const inline
Iterator for accessing credits for this album, except artist credit. The Artist Credit is accessed via a dedicated method.
Returns
Iterator
gnsdk_uint32_t gracenote::metadata::GnTrack::CurrentPosition () const inline
Current position in milliseconds of the matched track. The current position tracks the approximate real time position of the playing audio track assuming it is not paused. Only available from GnMusicIdStream responses.
Returns
Current position in milliseconds
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnTrack::Duration () const inline
Duration in milliseconds of the track (only available if this is the matched track)
Returns
Duration in milliseconds
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnTrack::ExternalIds () const inline
Iterator for the track's external identifiers (ids from sources external to Gracenote, e.g., Amazon)
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnTrack::Genre (GnDataLevel level) const inline
Track's genre, e.g., Heavy Metal. List/locale dependent, multi-level field
Parameters
level [in] Data level
Returns
Genre
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::GnId () const inline
Track's Gracenote identifier
Returns
Gracenote identifier
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnTrack::GNSDK_CHECKED_CAST (GnTrack , GNSDK_GDO_TYPE_TRACK)
gnsdk_cstr_t gracenote::metadata::GnTrack::GnUId () const inline
Track's Gracenote unique identifier.
Returns
Gracenote unique identifier
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnTrack::IsFullResult () const inline
Flag indicating if response contains full (true) or partial (false) metadata.
Returns
True if full result, false otherwise
Note:
What constitutes a full result varies among the individual response types and results, and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::MatchConfidence () const inline
Confidence score (0-100) for match
Returns
Confidence score
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnTrack::MatchDuration () const inline
For MusicID-Stream fingerprint matches, this is the length of matched reference audio in milliseconds.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnTrack::Matched () const inline
Flag indicating if this is the matched track (true)
Returns
True if matched track, false otherwise
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
string_iterable gracenote::metadata::GnTrack::MatchedIdents () const inline
Track identifiers . Each identifier is associated with a file information object presented to Music-ID.
Returns
Matched identifier
gnsdk_cstr_t gracenote::metadata::GnTrack::MatchLookupType () const inline
Track's match type - the most authoritative matching type for a given file info object.
Returns
Match lookup type
Remarks:
The match type indicates which query type was the most authoritative matching type for a given file information object. MusicID-File does a query for each type of input data, and each type of input data has an authoritative rank. The match type indicates the highest authoritative matched type for this file information object. The match type is only useful in comparison to other match types. By itself it does not indicate a strong or poor match. The higher the match type, the more authoritative the identification process used. The following table lists the possible match type values:
Match Type Value
MIDF_MATCH_TYPE_TUI 11
MIDF_MATCH_TYPE_MUI 10
MIDF_MATCH_TYPE_TOC 9
MIDF_MATCH_TYPE_ASSOCIATED_ID 8
MIDF_MATCH_TYPE_WF 7
MIDF_MATCH_TYPE_TEXT_ON_WF 6
MIDF_MATCH_TYPE_ASSOCIATED_TEXT 5
MIDF_MATCH_TYPE_TEXT_TRACK 4
MIDF_MATCH_TYPE_TEXT_ALBUM 3
MIDF_MATCH_TYPE_TEXT_CONTRIBUTOR 2
MIDF_MATCH_TYPE_NONE 1
MIDF_MATCH_TYPE_INVALID 0
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnTrack::MatchPosition () const inline
Position in milliseconds of where we matched in the track
Returns
Match position in milliseconds
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnTrack::MatchScore () const inline
Track's match score - correlation between input text and matched track
Returns
Match score
Remarks:
The match score gives a correlation between the input text and the matched track, indicating how well the input text matched the track. However, any result that is returned is considered to be a good match. The match score is only useful in comparison to other match scores. By itself it does not indicate a strong or poor match.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::Mood (GnDataLevel level) const inline
Track's mood, e.g., Playful. List/locale dependent, multi-level field.
Parameters
level [in] Data level
Returns
Mood
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, and gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnTrack::Review () const inline
Fetch the album's review content object
Returns
Content object
gnsdk_cstr_t gracenote::metadata::GnTrack::TagId () const inline
Track's Gracenote Tag identifier (same as Product ID)
Returns
Gracenote Tag identifier
Remarks:
This method exists primarily to support legacy implementations. We recommend using the Product ID method to retrieve product related identifiers
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::Tempo (GnDataLevel level) const inline
Track's tempo, e.g., Fast. List/locale dependent, multi-leveled field.
Parameters
level [in] Data level
Returns
Tempo
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnTrack::Title () const inline
Track's official title.
Returns
Title
GnTitle gracenote::metadata::GnTrack::TitleClassical () const inline
Title presented using Gracenote's Three Line Solution for classical track (composer/work title/movement title)
Returns
Title
GnTitle gracenote::metadata::GnTrack::TitleRegional () const inline
Regional title. Locale/list dependent field.
Returns
Title
gnsdk_cstr_t gracenote::metadata::GnTrack::TrackNumber () const inline
Track's ordinal number on album.
Returns
Track number
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::Tui () const inline
Track's Gracenote Tui (title-unique identifier).
Returns
Tui
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnTrack::TuiTag () const inline
Track's Gracenote Tui Tag.
Returns
Tui Tag
References gracenote::metadata::GnDataObject::StringValue().
GnAudioWork gracenote::metadata::GnTrack::Work () const inline
Track's audio work.
Returns
Work
gnsdk_cstr_t gracenote::metadata::GnTrack::Year () const inline
Track's year.
Returns
Year
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.