GNSDK for Desktop: gracenote::metadata::GnVideoSeries Class Reference
gracenote::metadata::GnVideoSeries Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnVideoSeries ()
GnVideoSeries (gnsdk_gdo_handle_t gdoHandle)
GnVideoSeries (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnVideoSeries ()
gnsdk_cstr_t Audience () const
content_iterable Contents () const
gnsdk_cstr_t DateOriginalRelease () const
gnsdk_uint32_t Duration () const
gnsdk_cstr_t DurationUnits () const
externalid_iterable ExternalIds () const
gnsdk_uint32_t FranchiseCount () const
gnsdk_uint32_t FranchiseNum () const
GnTitle FranchiseTitle () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
gnsdk_cstr_t GnUId () const
bool IsFullResult () const
GnTitle OfficialTitle () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_cstr_t PlotSynopsis () const
gnsdk_cstr_t PlotSynopsisLanguage () const
gnsdk_cstr_t PlotTagline () const
gnsdk_cstr_t ProductId () const
product_iterable Products () const
GnRating Rating () const
gnsdk_cstr_t Reputation () const
gnsdk_cstr_t Scenario () const
season_iterable Seasons () const
gnsdk_cstr_t SerialType () const
gnsdk_cstr_t SettingEnvironment () const
gnsdk_cstr_t SettingTimePeriod () const
gnsdk_cstr_t Source () const
gnsdk_cstr_t StoryType () const
gnsdk_cstr_t Style () const
gnsdk_cstr_t Topic () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
video_credit_iterable VideoCredits () const
gnsdk_cstr_t VideoMood () const
gnsdk_cstr_t VideoProductionType () const
gnsdk_uint32_t VideoProductionTypeId () const
works_iterable Works ()
gnsdk_cstr_t WorkType () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoSeries::GnVideoSeries () inline
gracenote::metadata::GnVideoSeries::GnVideoSeries (gnsdk_gdo_handle_t gdoHandle) inline
gracenote::metadata::GnVideoSeries::GnVideoSeries (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
virtual gracenote::metadata::GnVideoSeries::~GnVideoSeries () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Audience () const inline
Audience, e.g., "Young Adult"
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory. To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
content_iterable gracenote::metadata::GnVideoSeries::Contents () const inline
Iterator for the content (cover art, biography, etc.) associated with this video work.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::DateOriginalRelease () const inline
Original release date. Available for video Products, Features, and Works.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeries::Duration () const inline
Duration value such as "3600" (seconds) for a 60-minute program. Available for video Chapters, Features, Products, Seasons, Series, and Works.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::DurationUnits () const inline
Duration units type (seconds, "SEC"). Available for video Chapters, Features, Products, Seasons, Series, and Works.
References gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnVideoSeries::ExternalIds () const inline
Iterator for external IDs, supports Link data.
Remarks:
External IDs identify a source external to Gracenote (e.g., NetFlix), that also have an identifier for this work. The ordinal parameter indicates the n'th child external ID to retrieve.
gnsdk_uint32_t gracenote::metadata::GnVideoSeries::FranchiseCount () const inline
Franchise count.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeries::FranchiseNum () const inline
Franchise number.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoSeries::FranchiseTitle () const inline
Franchise title object.
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Genre (GnDataLevel level) const inline
Genre, e.g., Comedy. This ia a list/locale dependent, multi-level object.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::GnId () const inline
Gracenote ID.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::GnUId () const inline
Gracenote unique ID.
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnVideoSeries::IsFullResult () const inline
Flag indicating if response result contains full (true) or partial metadata.
Note:
What constitutes a full result varies among responses and results and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoSeries::OfficialTitle () const inline
Official title object
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Origin (GnDataLevel level) const inline
Geographic location, e.g., "New York City". This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::PlotSynopsis () const inline
Plot synopsis, e.g., "A semi-autobiographical coming-of-age story"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::PlotSynopsisLanguage () const inline
Plot synopsis language, e.g., English
Remarks:
The language depends on availability: information in the language set for the locale may not be available, and the object's information may be available only in its default official language. For example, if a locale's set language is Spanish, but the object's information is available only in English, this value returns as English.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::PlotTagline () const inline
Plot tagline, e.g., "If you forgot what terror was like...its back"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::ProductId () const inline
Product ID, aka Tag ID
Remarks:
This value can be stored or transmitted - it is a static identifier for the current content and will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
product_iterable gracenote::metadata::GnVideoSeries::Products () const inline
Iterator for child video products
Remarks:
The ordinal parameter specifies the n'th child
GnRating gracenote::metadata::GnVideoSeries::Rating () const inline
Rating object
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Reputation () const inline
Reputation, e.g., Cult
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Scenario () const inline
Scenario, e.g., Drama
Remarks:
This is a list-based value requiring that the list be loaded into memory through a successful call to gnsdk_manager_locale_load.
To render locale-dependent information for list-based values, the application must call gnsdk_manager_locale_load and possibly also gnsdk_sdkmanager_gdo_set_locale. The application returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::GnDataObject::StringValue().
season_iterable gracenote::metadata::GnVideoSeries::Seasons () const inline
Iterator for child seasons
Remarks:
The ordinal parameter indicates the n'th child video season to retrieve. Video product types are generally available from video season Gracenote data objects.
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::SerialType () const inline
Video serial type, e.g., Episode.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory To render locale-dependent information for list-based values, the application must allocate a GnLocale objec. The SDK returns a LocaleNotLoaded message when locale information is not set prior to a request for a list-based value
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::SettingEnvironment () const inline
Setting environment, e.g., Skyscraper.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::SettingTimePeriod () const inline
Historical time period such as "Elizabethan Era, 1558-1603"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Source () const inline
Source, e.g., "Phillip K. Dick short story".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::StoryType () const inline
Story type, e.g., "Love Story"
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Style () const inline
Style, such as "Film Noir"
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Topic () const inline
Topic, such as Racing
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::Tui () const inline
TUI (title unique identifier)
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::TuiTag () const inline
TUI tag
References gracenote::metadata::GnDataObject::StringValue().
video_credit_iterable gracenote::metadata::GnVideoSeries::VideoCredits () const inline
Iterable for child video credits.
Remarks:
The ordinal parameter indicates the n'th child video credit to retrieve.
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::VideoMood () const inline
Video mood, e.g., Somber
Remarks:
Mood information for music and video, depending on the respective calling type.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::VideoProductionType () const inline
Production type, e.g., Animation. This is a list/locale dependent field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory. To render locale-dependent information for list-based values, the application must allocate a GnLocale object. The SDK returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeries::VideoProductionTypeId () const inline
Production type identifier
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
works_iterable gracenote::metadata::GnVideoSeries::Works () inline
Iterator for child works.
gnsdk_cstr_t gracenote::metadata::GnVideoSeries::WorkType () const inline
Work type, e.g., Musical
Remarks:
This is a list-based value requiring that the list be loaded into memory through a successful call to gnsdk_manager_locale_load.
To render locale-dependent information for list-based values, the application must call gnsdk_manager_locale_load and possibly also gnsdk_sdkmanager_gdo_set_locale. The application returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.