GNSDK for Desktop: gracenote::metadata::GnExternalId Class Reference
gracenote::metadata::GnExternalId Class Reference
Public Member Functions
GnExternalId ()
GnExternalId (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnExternalId ()
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnExternalId, GNSDK_GDO_TYPE_EXTERNAL_ID)
gnsdk_cstr_t Source () const
gnsdk_cstr_t Type () const
gnsdk_cstr_t Value () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Third-party identifier used to match identified media to merchandise IDs in online stores and other services
Constructor & Destructor Documentation
gracenote::metadata::GnExternalId::GnExternalId () inline
Constructs empty GnExternalId object
gracenote::metadata::GnExternalId::GnExternalId (gnsdk_gdo_handle_t gdoHandle) inline
Construct a GnExternalId object with a native handle
Parameters
gdoHandle [in] Native handle
virtual gracenote::metadata::GnExternalId::~GnExternalId () inline virtual
Member Function Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnExternalId::GNSDK_CHECKED_CAST (GnExternalId , GNSDK_GDO_TYPE_EXTERNAL_ID)
gnsdk_cstr_t gracenote::metadata::GnExternalId::Source () const inline
External ID source (e.g., Amazon)
Returns
External ID source
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnExternalId::Type () const inline
External ID type
Returns
External ID type
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnExternalId::Value () const inline
External ID value
Returns
External ID value
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.