GNSDK for Desktop: gracenote::metadata::GnDataMatch Class Reference
gracenote::metadata::GnDataMatch Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnDataMatch ()
GnDataMatch (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnDataMatch ()
GnAlbum GetAsAlbum () const
GnContributor GetAsContributor () const
bool IsAlbum () const
bool IsContributor () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Represents a match to query where any type of match is desired, album or contributor.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnDataMatch::GnDataMatch () inline
Constructs empty GnDataMatch object
gracenote::metadata::GnDataMatch::GnDataMatch (gnsdk_gdo_handle_t gdoHandle) inline explicit
Constructs a GnDataMatch object from a native handle
Parameters
gdoHandle [in] Native handle
virtual gracenote::metadata::GnDataMatch::~GnDataMatch () inline virtual
Member Function Documentation
GnAlbum gracenote::metadata::GnDataMatch::GetAsAlbum () const inline
If album, get match as album object
Returns
Album
References IsAlbum().
GnContributor gracenote::metadata::GnDataMatch::GetAsContributor () const inline
If contributor, get match as contributor object
Returns
Contributor
References IsContributor().
bool gracenote::metadata::GnDataMatch::IsAlbum () const inline
Flag indicating if match is album
Returns
True if album is a match, false otherwise
References gracenote::metadata::GnDataObject::GetType(), and gracenote::gnstd::gn_strcmp().
Referenced by GetAsAlbum().
bool gracenote::metadata::GnDataMatch::IsContributor () const inline
Flag indicating if match is contributor
Returns
True if result is a contributor, false otherwise
References gracenote::metadata::GnDataObject::GetType(), and gracenote::gnstd::gn_strcmp().
Referenced by GetAsContributor().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.