GNSDK for Desktop: gracenote::gnconvert Class Reference
gracenote::gnconvert Class Reference
Static Public Member Functions
static gnsdk_cstr_t _convertContentTypeCppC (GnContentType contentType)
static gnsdk_cstr_t _convertDescCppC (GnDescriptor descriptor)
static GnDescriptor _convertDescriptorCCpp (gnsdk_cstr_t c_descriptor)
static gnsdk_cstr_t _convertLangCppC (GnLanguage language)
static GnLanguage _convertLanguageCCpp (gnsdk_cstr_t c_language)
static GnRegion _convertRegionCCpp (gnsdk_cstr_t c_region)
static gnsdk_cstr_t _convertRegionCppC (GnRegion region)
Detailed Description
Various methods for converting to and from native values For internal use.
Member Function Documentation
static gnsdk_cstr_t gracenote::gnconvert::_convertContentTypeCppC (GnContentType contentType) inline static
Convert enumerated content type to native content type
Parameters
lanaguage [in] Enumerated content type
Returns
Native content type value
References gracenote::kContentTypeArtistNews, gracenote::kContentTypeBiography, gracenote::kContentTypeImageArtist, gracenote::kContentTypeImageCover, gracenote::kContentTypeImageVideo, gracenote::kContentTypeListenerComments, gracenote::kContentTypeNews, gracenote::kContentTypeReleaseComments, and gracenote::kContentTypeReview.
Referenced by gracenote::metadata::GnTrack::Content(), gracenote::metadata::GnAlbum::Content(), and gracenote::metadata::GnContributor::Content().
static gnsdk_cstr_t gracenote::gnconvert::_convertDescCppC (GnDescriptor descriptor) inline static
Convert enumerated descriptor to native descriptor
Parameters
lanaguage [in] Enumerated descriptor
Returns
Native descriptor value
References gracenote::kDescriptorDefault, gracenote::kDescriptorDetailed, and gracenote::kDescriptorSimplified.
static GnDescriptor gracenote::gnconvert::_convertDescriptorCCpp (gnsdk_cstr_t c_descriptor) inline static
Convert native descriptor to enumerated descriptor
Parameters
c_region [in] Native descriptor
Returns
Enumerated descriptor
References gracenote::gnstd::gn_strcmp(), gracenote::kDescriptorDefault, gracenote::kDescriptorDetailed, and gracenote::kDescriptorSimplified.
static gnsdk_cstr_t gracenote::gnconvert::_convertLangCppC (GnLanguage language) inline static
Convert enumerated language to native language
Parameters
lanaguage [in] Enumerated langauge
Returns
Native language value
References gracenote::kLanguageArabic, gracenote::kLanguageBulgarian, gracenote::kLanguageChineseSimplified, gracenote::kLanguageChineseTraditional, gracenote::kLanguageCroatian, gracenote::kLanguageCzech, gracenote::kLanguageDanish, gracenote::kLanguageDutch, gracenote::kLanguageEnglish, gracenote::kLanguageFarsi, gracenote::kLanguageFinnish, gracenote::kLanguageFrench, gracenote::kLanguageGerman, gracenote::kLanguageGreek, gracenote::kLanguageHungarian, gracenote::kLanguageIndonesian, gracenote::kLanguageInvalid, gracenote::kLanguageItalian, gracenote::kLanguageJapanese, gracenote::kLanguageKorean, gracenote::kLanguageNorwegian, gracenote::kLanguagePolish, gracenote::kLanguagePortuguese, gracenote::kLanguageRomanian, gracenote::kLanguageRussian, gracenote::kLanguageSerbian, gracenote::kLanguageSlovak, gracenote::kLanguageSpanish, gracenote::kLanguageSwedish, gracenote::kLanguageThai, gracenote::kLanguageTurkish, and gracenote::kLanguageVietnamese.
static GnLanguage gracenote::gnconvert::_convertLanguageCCpp (gnsdk_cstr_t c_language) inline static
Convert native language to enumerated language
Parameters
c_region [in] Native language
Returns
Enumerated language
References gracenote::gnstd::gn_strcmp(), gracenote::kLanguageArabic, gracenote::kLanguageBulgarian, gracenote::kLanguageChineseSimplified, gracenote::kLanguageChineseTraditional, gracenote::kLanguageCroatian, gracenote::kLanguageCzech, gracenote::kLanguageDanish, gracenote::kLanguageDutch, gracenote::kLanguageEnglish, gracenote::kLanguageFarsi, gracenote::kLanguageFinnish, gracenote::kLanguageFrench, gracenote::kLanguageGerman, gracenote::kLanguageGreek, gracenote::kLanguageHungarian, gracenote::kLanguageIndonesian, gracenote::kLanguageItalian, gracenote::kLanguageJapanese, gracenote::kLanguageKorean, gracenote::kLanguageNorwegian, gracenote::kLanguagePolish, gracenote::kLanguagePortuguese, gracenote::kLanguageRomanian, gracenote::kLanguageRussian, gracenote::kLanguageSerbian, gracenote::kLanguageSlovak, gracenote::kLanguageSpanish, gracenote::kLanguageSwedish, gracenote::kLanguageThai, gracenote::kLanguageTurkish, and gracenote::kLanguageVietnamese.
static GnRegion gracenote::gnconvert::_convertRegionCCpp (gnsdk_cstr_t c_region) inline static
Convert native region to enumerated region
Parameters
c_region [in] Native region
Returns
Enumerated region
References gracenote::gnstd::gn_strcmp(), gracenote::kRegionChina, gracenote::kRegionDefault, gracenote::kRegionEurope, gracenote::kRegionGlobal, gracenote::kRegionIndia, gracenote::kRegionJapan, gracenote::kRegionKorea, gracenote::kRegionLatinAmerica, gracenote::kRegionNorthAmerica, gracenote::kRegionTaiwan, and gracenote::kRegionUS.
static gnsdk_cstr_t gracenote::gnconvert::_convertRegionCppC (GnRegion region) inline static
Convert enumerated region to native region
Parameters
lanaguage [in] Enumerated region
Returns
Native region value
References gracenote::kRegionChina, gracenote::kRegionDefault, gracenote::kRegionEurope, gracenote::kRegionGlobal, gracenote::kRegionIndia, gracenote::kRegionJapan, gracenote::kRegionKorea, gracenote::kRegionLatinAmerica, gracenote::kRegionNorthAmerica, gracenote::kRegionTaiwan, and gracenote::kRegionUS.
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:49.