GNSDK for Desktop: gracenote::metadata::GnVideoWork Class Reference
gracenote::metadata::GnVideoWork Class Reference
Public Member Functions
GnVideoWork ()
GnVideoWork (gnsdk_gdo_handle_t gdoHandle)
GnVideoWork (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnVideoWork ()
gnsdk_cstr_t Audience () const
content_iterable Contents () const
gnsdk_cstr_t DateOriginalRelease () const
gnsdk_uint32_t Duration () const
gnsdk_cstr_t DurationUnits () const
externalid_iterable ExternalIds () const
gnsdk_uint32_t FranchiseCount () const
gnsdk_uint32_t FranchiseNum () const
GnTitle FranchiseTitle () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnVideoWork, GNSDK_GDO_TYPE_VIDEO_WORK)
gnsdk_cstr_t GnUId () const
bool IsFullResult () const
GnTitle OfficialTitle () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_cstr_t PlotSynopsis () const
gnsdk_cstr_t PlotSynopsisLanguage () const
gnsdk_cstr_t PlotTagline () const
gnsdk_cstr_t ProductId () const
product_iterable Products ()
GnRating Rating () const
gnsdk_cstr_t Reputation () const
gnsdk_cstr_t Scenario () const
gnsdk_uint32_t SeasonCount () const
gnsdk_uint32_t SeasonEpisode () const
gnsdk_uint32_t SeasonEpisodeCount () const
gnsdk_uint32_t SeasonNumber () const
season_iterable Seasons () const
gnsdk_cstr_t SerialType () const
series_iterable Series () const
gnsdk_uint32_t SeriesEpisode () const
gnsdk_uint32_t SeriesEpisodeCount () const
GnTitle SeriesTitle () const
gnsdk_cstr_t SettingEnvironment () const
gnsdk_cstr_t SettingTimePeriod () const
gnsdk_cstr_t Source () const
gnsdk_cstr_t StoryType () const
gnsdk_cstr_t Style () const
gnsdk_cstr_t Topic () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiMatchProduct () const
gnsdk_cstr_t TuiTag () const
video_credit_iterable VideoCredits () const
gnsdk_cstr_t VideoMood () const
gnsdk_cstr_t VideoProductionType () const
gnsdk_uint32_t VideoProductionTypeId () const
gnsdk_cstr_t WorkType () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Constructor & Destructor Documentation
gracenote::metadata::GnVideoWork::GnVideoWork () inline
gracenote::metadata::GnVideoWork::GnVideoWork (gnsdk_gdo_handle_t gdoHandle) inline
gracenote::metadata::GnVideoWork::GnVideoWork (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
virtual gracenote::metadata::GnVideoWork::~GnVideoWork () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Audience () const inline
Audience type, e.g.,"Kids and Family", "African-American", or "Young Adult".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
content_iterable gracenote::metadata::GnVideoWork::Contents () const inline
Iterator for the content (cover art, biography, etc.) associated with this video work.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnVideoWork::DateOriginalRelease () const inline
Video's original release date.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::Duration () const inline
Duration value in seconds such as "3600" (seconds) for a 60-minute program.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::DurationUnits () const inline
Duration units value (seconds, "SEC").
References gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnVideoWork::ExternalIds () const inline
Iterator for external IDs. External IDs are 3rd party IDs used to cross link this metadata to 3rd party services, e.g. Amazon
gnsdk_uint32_t gracenote::metadata::GnVideoWork::FranchiseCount () const inline
Franchise count
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::FranchiseNum () const inline
Franchise number
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoWork::FranchiseTitle () const inline
Franchise title object
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Genre (GnDataLevel level) const inline
Genre - e.g., comedy. This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
This is a multi-level field requiring a GnDataLevel parameter
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::GnId () const inline
Gracenote ID.
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoWork::GNSDK_CHECKED_CAST (GnVideoWork , GNSDK_GDO_TYPE_VIDEO_WORK)
gnsdk_cstr_t gracenote::metadata::GnVideoWork::GnUId () const inline
Gracenote unique identifier
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnVideoWork::IsFullResult () const inline
Flag indicating if result contains full (true) or partial metadata.
Note:
What constitutes a full result varies among response types and results and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoWork::OfficialTitle () const inline
Official title object
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Origin (GnDataLevel level) const inline
Geographic location, e.g., "New York City". This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that the list be loaded into memory through a successful call to gnsdk_manager_locale_load.
To render locale-dependent information for list-based values, the application must call gnsdk_manager_locale_load and possibly also gnsdk_sdkmanager_gdo_set_locale. The application returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::PlotSynopsis () const inline
Plot synopsis e.g., "A semi-autobiographical coming-of-age story"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::PlotSynopsisLanguage () const inline
Plot synopis language, e.g., English
Remarks:
The language of a returned object depends on availability. Information in the language set for the locale may not be available, and the object's information may be available only in its default official language. For example, if a locale's set language is Spanish, but the object's information is available only in English, this value returns as English.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::PlotTagline () const inline
Plot tagline, e.g., "The Third Dimension is Terror"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::ProductId () const inline
Product ID aka Tag ID
Remarks:
This value which can be stored or transmitted - it can be used as a static identifier for the current content and will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
product_iterable gracenote::metadata::GnVideoWork::Products () inline
Iterator for child products
GnRating gracenote::metadata::GnVideoWork::Rating () const inline
Rating object
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Reputation () const inline
Film's reputation, e.g., "Classic", "Chick Flick", or "Cult". This is a critical or popular "value" that is assigned to a work, usually long after the work was released, though some works may qualify shortly after release (e.g., "instant classic" or "blockbuster release").
Remarks:
This is a list-based value requiring that the list be loaded into memory through a successful call to gnsdk_manager_locale_load.
To render locale-dependent information for list-based values, the application must call gnsdk_manager_locale_load and possibly also gnsdk_sdkmanager_gdo_set_locale. The application returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Scenario () const inline
Scenario, e.g., "Action", "Comedy", and "Drama".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeasonCount () const inline
Season count value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeasonEpisode () const inline
Season episode value.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeasonEpisodeCount () const inline
Season episode count
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeasonNumber () const inline
Season number value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
season_iterable gracenote::metadata::GnVideoWork::Seasons () const inline
Iterator for child seasons.
Remarks:
The ordinal parameter specifies the n'th child video Season to retrieve. Video product types are generally available from GNSDK_GDO_TYPE_RESPONSE_VIDEO_SEASON GDOs.
gnsdk_cstr_t gracenote::metadata::GnVideoWork::SerialType () const inline
Supported video serial type such as Series or Episode
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
series_iterable gracenote::metadata::GnVideoWork::Series () const inline
Iterator for child series'
Remarks:
The ordinal parameter specifies the the n'th child video Series to retrieve. Video Series types are generally available from GNSDK_GDO_TYPE_RESPONSE_VIDEO_SERIES GDOs.
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeriesEpisode () const inline
Series episode value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::SeriesEpisodeCount () const inline
Series episode count
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoWork::SeriesTitle () const inline
Series title object.
gnsdk_cstr_t gracenote::metadata::GnVideoWork::SettingEnvironment () const inline
Physical environment - this is not specific location, but rather a general (or generic) location. For example: Prison, High School, Skyscraper, Desert, etc.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::SettingTimePeriod () const inline
Historical time setting, e.g., "Elizabethan Era 1558-1603", or "Jazz Age 1919-1929".
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Source () const inline
Story concept source, e.g., "Fairy Tales and Nursery Rhymes".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::StoryType () const inline
Story type, e.g., "Love Story".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Style () const inline
Film style, e.g., "Film Noir".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Topic () const inline
Film topic, e.g., "Racing" or "Teen Angst".
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::Tui () const inline
TUI (title-unique identifier)
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::TuiMatchProduct () const inline
Second TUI, if it exists. This TUI is used for matching partial Products objects to full Works objects. Use this value to ensure correct Tui value matching for cases when a video Product GDO contains multiple partial Work GDOs. Each partial Work GDO corresponds to a full Works object, and each full Works object contains the GNSDK_GDO_VALUE_TUI value, incremented by one digit to maintain data integrity with Gracenote Service. The GNSDK_GDO_VALUE_TUI_MATCH_PRODUCT maps the partial Works object Tui value to the full Works object.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::TuiTag () const inline
TUI tag
References gracenote::metadata::GnDataObject::StringValue().
video_credit_iterable gracenote::metadata::GnVideoWork::VideoCredits () const inline
Iterator for child credits. For music types, this includes all credits except the artist credit.
gnsdk_cstr_t gracenote::metadata::GnVideoWork::VideoMood () const inline
Mood, e.g., Playful
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::VideoProductionType () const inline
Video production type, e.g., Animation. This is a list/locale dependent value.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoWork::VideoProductionTypeId () const inline
Video production type ID
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoWork::WorkType () const inline
Work type, e.g., Musical
Remarks:
This is a list-based value requiring that the list be loaded into memory through a successful call to gnsdk_manager_locale_load.
To render locale-dependent information for list-based values, the application must call gnsdk_manager_locale_load and possibly also gnsdk_sdkmanager_gdo_set_locale. The application returns a LocaleNotLoaded message when locale information is not set prior to a request for list-based value information.
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.