GNSDK for Desktop: gracenote::metadata::GnVideoLayer Class Reference
gracenote::metadata::GnVideoLayer Class Reference
Public Member Functions
GnVideoLayer ()
GnVideoLayer (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnVideoLayer ()
gnsdk_cstr_t AspectRatio () const
gnsdk_cstr_t AspectRatioType () const
feature_iterable Features () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnVideoLayer, GNSDK_GDO_TYPE_VIDEO_LAYER)
bool Matched () const
gnsdk_cstr_t MediaType () const
gnsdk_uint32_t Ordinal () const
gnsdk_cstr_t RegionCode () const
gnsdk_cstr_t TvSystem () const
gnsdk_cstr_t VideoRegion () const
gnsdk_cstr_t VideoRegionDesc () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Both DVDs and Blu-ray Discs can be dual layer. These discs are only writable on one side of the disc, but contain two layers on that single side for writing data to. Dual-Layer recordable DVDs come in two formats: DVD-R DL and DVD+R DL. They can hold up to 8.5GB on the two layers. Dual-layer Blu-ray discs can store 50 GB of data (25GB on each layer)
Constructor & Destructor Documentation
gracenote::metadata::GnVideoLayer::GnVideoLayer () inline
gracenote::metadata::GnVideoLayer::GnVideoLayer (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnVideoLayer::~GnVideoLayer () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::AspectRatio () const inline
Aspect ratio - describes the proportional relationship between the video's width and its height expressed as two numbers separated by a colon
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::AspectRatioType () const inline
Aspect ratio type, e.g. Standard
References gracenote::metadata::GnDataObject::StringValue().
feature_iterable gracenote::metadata::GnVideoLayer::Features () const inline
Iterator for child video features.
Remarks:
The ordinal parameter specifies the n'th child video feature to retrieve.
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoLayer::GNSDK_CHECKED_CAST (GnVideoLayer , GNSDK_GDO_TYPE_VIDEO_LAYER)
bool gracenote::metadata::GnVideoLayer::Matched () const inline
Matched boolean value indicating whether this object is the one that matched the input criteria.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::MediaType () const inline
Video media type such as Audio-CD, Blu-ray, DVD, or HD DVD.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, your application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoLayer::Ordinal () const inline
Ordinal value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::RegionCode () const inline
Region code, e.g., FE - France
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::TvSystem () const inline
TV system value, e.g., NTSC.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::VideoRegion () const inline
Video product region value from the current type, e.g., 1. This is a list/locale dependent value.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoLayer::VideoRegionDesc () const inline
Video product region, e.g., USA, Canada, US Territories, Bermuda, and Cayman Islands.
Remarks:
This is a list-based value requiring that a list or locale be loaded into memory.
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. A LocaleNotLoaded message is returned when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.