GNSDK for Desktop: gracenote::metadata::GnResponseContributors Class Reference
gracenote::metadata::GnResponseContributors Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnResponseContributors ()
GnResponseContributors (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnResponseContributors ()
contributor_iterable Contributors () const
bool NeedsDecision () const
gnsdk_uint32_t RangeEnd () const
gnsdk_uint32_t RangeStart () const
gnsdk_uint32_t RangeTotal () const
gnsdk_uint32_t ResultCount () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Remarks about range values:
If you do not set a starting value, the default behavior is to return the first set of results. Range values are available to aid in paging results. Gracenote Service limits the number of responses returned in any one request, so the range values are available to indicate the total number of results, and where the current results fit in within that total.
Important:
The number of results actually returned for a query may not equal the number of results requested. To accurately iterate through results, always check the range start, end, and total values and the responses returned by Gracenote Service for the query (or queries). Ensure that you are incrementing by using the actual last range end value plus one (range_end+1), and not by simply using the initial requested value.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnResponseContributors::GnResponseContributors () inline
gracenote::metadata::GnResponseContributors::GnResponseContributors (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnResponseContributors::~GnResponseContributors () inline virtual
Member Function Documentation
contributor_iterable gracenote::metadata::GnResponseContributors::Contributors () const inline
Iterator for child contributors.
bool gracenote::metadata::GnResponseContributors::NeedsDecision () const inline
Flag indicating if response match(es) need a user or app decision - either multiple matches returned or less than perfect single match..
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnResponseContributors::RangeEnd () const inline
Ordinal of the last result in the returned range.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnResponseContributors::RangeStart () const inline
Ordinal of the first result in the returned range.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnResponseContributors::RangeTotal () const inline
Estimated total number of results possible.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnResponseContributors::ResultCount () const inline
Total number of results
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.