GNSDK for Desktop: gracenote::GnObject Class Reference
gracenote::GnObject Class Reference
Public Member Functions
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Detailed Description
Base object for managing objects in natively running GNSDK.
Member Function Documentation
bool gracenote::GnObject::IsNull () const inline
Get flag indicating if GnObject contains no native object handle
Returns
True if null, false otherwise
Referenced by gracenote::metadata::GnContent::ContentType().
virtual bool gracenote::GnObject::operator!= (const GnObject & rhs) const inline virtual
operator !=
References operator==().
virtual bool gracenote::GnObject::operator== (const GnObject & rhs) const inline virtual
operator ==
Referenced by operator!=().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:49.