GNSDK for Desktop: gracenote::metadata::GnDataObject Class Reference
gracenote::metadata::GnDataObject Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Static Public Member Functions
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Gracenote Data Object - encapsulation of GNSDK delivered media elements and metadata.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnDataObject::GnDataObject () inline
gracenote::metadata::GnDataObject::GnDataObject (const GnDataObject & obj) inline
gracenote::metadata::GnDataObject::GnDataObject (gnsdk_gdo_handle_t gdoHandle) inline
gracenote::metadata::GnDataObject::GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError) inline
Member Function Documentation
GnDataObject gracenote::metadata::GnDataObject::Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal = 1) const inline
Child data object specified by the key and ordinal
Parameters
childKey [in] Child key to return
childOrdinal [in] 1-based specifier of a child where multiple values for a key exist
Remarks:
Use this function to count children of a specific data instance; note that only those children accessible in the current type are considered.
gnsdk_uint32_t gracenote::metadata::GnDataObject::ChildCount (gnsdk_cstr_t childKey) const inline
Number of children available for a given key.
Parameters
childKey [in] Child key to count
Returns
Count
Remarks:
Use this function to count children of a specific data instance; note that only those children accessible in the current type are considered.
When this function successfully counts zero (0) occurrences of the child key with no errors, the method returns successfully.
Referenced by gracenote::metadata::gn_gdo_provider< _GdoType >::count().
template<typename gdoType > gdoType gracenote::metadata::GnDataObject::ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal = 1) const inline
Child data object specified by the key and ordinal
Parameters
childKey [in] Child key to return
childOrdinal [in] 1-based specifier of a child where multiple values for a key exist
Remarks:
Use this function to count children of a specific data instance; note that only those children accessible in the current type are considered.
static GnDataObject gracenote::metadata::GnDataObject::CreateFromXml (gnsdk_cstr_t xml) throw (GnError) inline static
Create Gracenote Data Object from XML
Parameters
xml [in] XML string
Returns
Gracenote data object
static GnDataObject gracenote::metadata::GnDataObject::Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError) inline static
Deserialize GNSDK data object
Parameters
serializedGdo [in] Serialized Gracenote data object string
Returns
Gracenote data object
gnsdk_cstr_t gracenote::metadata::GnDataObject::GetType () const throw (GnError) inline
Data object's type.
Returns
Type string
Remarks:
The data object's contents are not clearly defined. Use this API to retrieve a data object's type, as this enables the application to more accurately determine what data the specific data it contains. Typically an application will use data objects subclassed from the data object, which do specifically define a type.
References gracenote::gnstd::kEmptyString.
Referenced by gracenote::metadata::GnDataMatch::IsAlbum(), and gracenote::metadata::GnDataMatch::IsContributor().
bool gracenote::metadata::GnDataObject::IsType (gnsdk_cstr_t strType) const throw (GnError) inline
Flag indicating if object is specified type
Parameters
strType [in] Type string
Returns
True if object is if provided type, false otherwise
void gracenote::metadata::GnDataObject::Locale (const GnLocale & locale) const throw (GnError) inline
Applies lists to use for retrieving and rendering locale-related values.
Parameters
locale Locale to apply to this data object
Remarks:
Use this function to set the locale of retrieved and rendered locale-dependent data for this data object. This function overrides any applicable global locale defaults set elsewhere.
Locale Language Support
This function supports all locale languages and successfully assigns a locale for this data object. The locale is used for future calls to get data values when locale-dependent values are requested.
When list-based locale-specific values are requested from this data object they are returned only if an applicable locale has been successfully set by this method or a default locale has been successfully set elsehwere.
When a non-list-based locale-specific values are requested from this data object they are returned only if these values are available from Gracenote Service or the locale database (where online queries are not accessible or permitted). If not, the application uses the default (or "official") locale data for these values. For example, plot values are non-list-based. If a plot summary value is available only in the English language, and the specific locale is defined for the Spanish language, the application displays the plot summary in the English language.
gnsdk_gdo_handle_t gracenote::metadata::GnDataObject::native () const inline
Returns the native handle for the data object.
Returns
Native handle
template<typename gdoType > gdoType gracenote::metadata::GnDataObject::Reflect () const inline
Reflect
GnString gracenote::metadata::GnDataObject::Render (const GnRenderOptions & options) const throw (GnError) inline
Renders contents of the data object as an XML string.
Parameters
options [in] Render options object
Returns
Rendered output string
References gracenote::GnString::manage().
GnString gracenote::metadata::GnDataObject::Serialize () const throw (GnError) inline
Serialize this object
Returns
Serialize Gracenote data object string
References gracenote::GnString::manage().
gnsdk_cstr_t gracenote::metadata::GnDataObject::StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal = 1) const inline
Returns media or metadata value as a string based on the provided key and ordinal.
Parameters
valueKey [in] Key of the value to return
ordinal [in] 1-based specifier of a value where multiple values for a key exist
Returns
Value
References gracenote::gnstd::kEmptyString.
Referenced by gracenote::playlist::GnPlaylistAttributes::AlbumName(), gracenote::playlist::GnPlaylistAttributes::ArtistName(), gracenote::playlist::GnPlaylistAttributes::ArtistType(), gracenote::metadata::GnVideoCredit::ArtistType(), gracenote::metadata::GnContributor::ArtistType(), gracenote::metadata::GnVideoFeature::AspectRatio(), gracenote::metadata::GnVideoLayer::AspectRatio(), gracenote::metadata::GnVideoProduct::AspectRatio(), gracenote::metadata::GnVideoFeature::AspectRatioType(), gracenote::metadata::GnVideoLayer::AspectRatioType(), gracenote::metadata::GnVideoProduct::AspectRatioType(), gracenote::metadata::GnVideoSeason::Audience(), gracenote::metadata::GnVideoSeries::Audience(), gracenote::metadata::GnVideoWork::Audience(), gracenote::metadata::GnContributor::BiographyVideo(), gracenote::metadata::GnContributor::BirthDate(), gracenote::metadata::GnContributor::BirthPlace(), gracenote::metadata::GnAsset::Bytes(), gracenote::metadata::GnRole::Category(), gracenote::metadata::GnVideoCredit::CharacterName(), gracenote::metadata::GnContributor::CollaboratorResult(), gracenote::metadata::GnVideoProduct::CommerceType(), gracenote::metadata::GnAlbum::Compilation(), gracenote::metadata::GnAudioWork::CompositionForm(), gracenote::metadata::GnContent::ContentType(), gracenote::metadata::GnTrack::CurrentPosition(), gracenote::metadata::GnVideoSeason::DateOriginalRelease(), gracenote::metadata::GnVideoSeries::DateOriginalRelease(), gracenote::metadata::GnVideoWork::DateOriginalRelease(), gracenote::metadata::GnVideoFeature::DateOriginalRelease(), gracenote::metadata::GnVideoProduct::DateOriginalRelease(), gracenote::metadata::GnVideoFeature::DateRelease(), gracenote::metadata::GnVideoProduct::DateRelease(), gracenote::metadata::GnContributor::DeathDate(), gracenote::metadata::GnContributor::DeathPlace(), gracenote::metadata::GnAsset::Dimension(), gracenote::metadata::GnAlbum::DiscInSet(), gracenote::metadata::GnName::Display(), gracenote::metadata::GnTitle::Display(), gracenote::metadata::GnTrack::Duration(), gracenote::metadata::GnVideoChapter::Duration(), gracenote::metadata::GnVideoSeason::Duration(), gracenote::metadata::GnVideoSeries::Duration(), gracenote::metadata::GnVideoWork::Duration(), gracenote::metadata::GnVideoFeature::Duration(), gracenote::metadata::GnVideoProduct::Duration(), gracenote::metadata::GnVideoChapter::DurationUnits(), gracenote::metadata::GnVideoSeason::DurationUnits(), gracenote::metadata::GnVideoSeries::DurationUnits(), gracenote::metadata::GnVideoWork::DurationUnits(), gracenote::metadata::GnVideoFeature::DurationUnits(), gracenote::metadata::GnVideoProduct::DurationUnits(), gracenote::metadata::GnTitle::Edition(), gracenote::playlist::GnPlaylistAttributes::Era(), gracenote::metadata::GnAudioWork::Era(), gracenote::metadata::GnVideoCredit::Era(), gracenote::metadata::GnContributor::Era(), gracenote::metadata::GnName::Family(), gracenote::metadata::GnVideoSeason::FranchiseCount(), gracenote::metadata::GnVideoSeries::FranchiseCount(), gracenote::metadata::GnVideoWork::FranchiseCount(), gracenote::metadata::GnVideoSeason::FranchiseNum(), gracenote::metadata::GnVideoSeries::FranchiseNum(), gracenote::metadata::GnVideoWork::FranchiseNum(), gracenote::playlist::GnPlaylistAttributes::Genre(), gracenote::metadata::GnAudioWork::Genre(), gracenote::metadata::GnVideoCredit::Genre(), gracenote::metadata::GnTrack::Genre(), gracenote::metadata::GnAlbum::Genre(), gracenote::metadata::GnVideoSeason::Genre(), gracenote::metadata::GnContributor::Genre(), gracenote::metadata::GnVideoSeries::Genre(), gracenote::metadata::GnVideoWork::Genre(), gracenote::metadata::GnVideoFeature::Genre(), gracenote::metadata::GnVideoProduct::Genre(), gracenote::metadata::gn_gdo_string_provider::get_data(), gracenote::metadata::GnName::Given(), gracenote::metadata::GnName::GlobalId(), gracenote::metadata::GnAlbum::GlobalId(), gracenote::metadata::GnAudioWork::GnId(), gracenote::metadata::GnTrack::GnId(), gracenote::metadata::GnVideoSeason::GnId(), gracenote::metadata::GnAlbum::GnId(), gracenote::metadata::GnContributor::GnId(), gracenote::metadata::GnVideoSeries::GnId(), gracenote::metadata::GnVideoWork::GnId(), gracenote::metadata::GnVideoDisc::GnId(), gracenote::metadata::GnVideoProduct::GnId(), gracenote::metadata::GnAudioWork::GnUId(), gracenote::metadata::GnTrack::GnUId(), gracenote::metadata::GnVideoSeason::GnUId(), gracenote::metadata::GnAlbum::GnUId(), gracenote::metadata::GnContributor::GnUId(), gracenote::metadata::GnVideoSeries::GnUId(), gracenote::metadata::GnVideoWork::GnUId(), gracenote::metadata::GnVideoDisc::GnUId(), gracenote::metadata::GnVideoProduct::GnUId(), gracenote::metadata::GnContent::Id(), gracenote::metadata::GnAlbum::IsClassical(), gracenote::metadata::GnTrack::IsFullResult(), gracenote::metadata::GnVideoSeason::IsFullResult(), gracenote::metadata::GnAlbum::IsFullResult(), gracenote::metadata::GnContributor::IsFullResult(), gracenote::metadata::GnVideoSeries::IsFullResult(), gracenote::metadata::GnVideoWork::IsFullResult(), gracenote::metadata::GnVideoProduct::IsFullResult(), gracenote::metadata::GnAlbum::Label(), gracenote::metadata::GnName::Language(), gracenote::metadata::GnAlbum::Language(), gracenote::metadata::GnTitle::Language(), gracenote::metadata::GnName::LanguageCode(), gracenote::metadata::GnAlbum::LanguageCode(), gracenote::metadata::GnTitle::LanguageCode(), gracenote::metadata::GnTitle::MainTitle(), gracenote::metadata::GnTrack::MatchConfidence(), gracenote::metadata::GnTrack::MatchDuration(), gracenote::metadata::GnTrack::Matched(), gracenote::metadata::GnVideoFeature::Matched(), gracenote::metadata::GnVideoLayer::Matched(), gracenote::metadata::GnVideoSide::Matched(), gracenote::metadata::GnVideoDisc::Matched(), gracenote::metadata::GnMatch::MatchInfo(), gracenote::metadata::GnTrack::MatchLookupType(), gracenote::metadata::GnTrack::MatchPosition(), gracenote::metadata::GnTrack::MatchScore(), gracenote::metadata::GnAlbum::MatchScore(), gracenote::metadata::GnContributor::MediaSpace(), gracenote::metadata::GnVideoLayer::MediaType(), gracenote::metadata::GnContent::MimeType(), gracenote::playlist::GnPlaylistAttributes::Mood(), gracenote::metadata::GnTrack::Mood(), gracenote::metadata::GnResponseTracks::NeedsDecision(), gracenote::metadata::GnResponseAlbums::NeedsDecision(), gracenote::metadata::GnResponseDataMatches::NeedsDecision(), gracenote::metadata::GnResponseVideoSuggestions::NeedsDecision(), gracenote::metadata::GnResponseVideoObjects::NeedsDecision(), gracenote::metadata::GnResponseContributors::NeedsDecision(), gracenote::metadata::GnResponseVideoSeries::NeedsDecision(), gracenote::metadata::GnResponseVideoSeasons::NeedsDecision(), gracenote::metadata::GnResponseVideoWork::NeedsDecision(), gracenote::metadata::GnResponseVideoProduct::NeedsDecision(), gracenote::metadata::GnVideoFeature::Notes(), gracenote::metadata::GnVideoSide::Notes(), gracenote::metadata::GnVideoDisc::Notes(), gracenote::metadata::GnVideoProduct::Notes(), gracenote::metadata::GnVideoChapter::Ordinal(), gracenote::metadata::GnVideoFeature::Ordinal(), gracenote::metadata::GnVideoLayer::Ordinal(), gracenote::metadata::GnVideoSide::Ordinal(), gracenote::metadata::GnVideoDisc::Ordinal(), gracenote::playlist::GnPlaylistAttributes::Origin(), gracenote::metadata::GnAudioWork::Origin(), gracenote::metadata::GnVideoCredit::Origin(), gracenote::metadata::GnVideoSeason::Origin(), gracenote::metadata::GnContributor::Origin(), gracenote::metadata::GnVideoSeries::Origin(), gracenote::metadata::GnVideoWork::Origin(), gracenote::metadata::GnVideoProduct::PackageLanguage(), gracenote::metadata::GnVideoProduct::PackageLanguageDisplay(), gracenote::metadata::GnVideoFeature::PlotSummary(), gracenote::metadata::GnVideoSeason::PlotSynopsis(), gracenote::metadata::GnVideoSeries::PlotSynopsis(), gracenote::metadata::GnVideoWork::PlotSynopsis(), gracenote::metadata::GnVideoFeature::PlotSynopsis(), gracenote::metadata::GnVideoSeason::PlotSynopsisLanguage(), gracenote::metadata::GnVideoSeries::PlotSynopsisLanguage(), gracenote::metadata::GnVideoWork::PlotSynopsisLanguage(), gracenote::metadata::GnVideoFeature::PlotSynopsisLanguage(), gracenote::metadata::GnVideoSeason::PlotTagline(), gracenote::metadata::GnVideoSeries::PlotTagline(), gracenote::metadata::GnVideoWork::PlotTagline(), gracenote::metadata::GnVideoFeature::PlotTagline(), gracenote::metadata::GnName::Prefix(), gracenote::metadata::GnTitle::Prefix(), gracenote::metadata::GnAudioWork::ProductId(), gracenote::metadata::GnVideoSeason::ProductId(), gracenote::metadata::GnContributor::ProductId(), gracenote::metadata::GnVideoSeries::ProductId(), gracenote::metadata::GnVideoWork::ProductId(), gracenote::metadata::GnVideoDisc::ProductId(), gracenote::metadata::GnVideoProduct::ProductId(), gracenote::metadata::GnResponseTracks::RangeEnd(), gracenote::metadata::GnResponseAlbums::RangeEnd(), gracenote::metadata::GnResponseDataMatches::RangeEnd(), gracenote::metadata::GnResponseVideoSuggestions::RangeEnd(), gracenote::metadata::GnResponseVideoObjects::RangeEnd(), gracenote::metadata::GnResponseContributors::RangeEnd(), gracenote::metadata::GnResponseVideoSeries::RangeEnd(), gracenote::metadata::GnResponseVideoSeasons::RangeEnd(), gracenote::metadata::GnResponseVideoWork::RangeEnd(), gracenote::metadata::GnResponseVideoProduct::RangeEnd(), gracenote::metadata::GnResponseTracks::RangeStart(), gracenote::metadata::GnResponseAlbums::RangeStart(), gracenote::metadata::GnResponseDataMatches::RangeStart(), gracenote::metadata::GnResponseVideoSuggestions::RangeStart(), gracenote::metadata::GnResponseVideoObjects::RangeStart(), gracenote::metadata::GnResponseContributors::RangeStart(), gracenote::metadata::GnResponseVideoSeries::RangeStart(), gracenote::metadata::GnResponseVideoSeasons::RangeStart(), gracenote::metadata::GnResponseVideoWork::RangeStart(), gracenote::metadata::GnResponseVideoProduct::RangeStart(), gracenote::metadata::GnResponseTracks::RangeTotal(), gracenote::metadata::GnResponseAlbums::RangeTotal(), gracenote::metadata::GnResponseDataMatches::RangeTotal(), gracenote::metadata::GnResponseVideoSuggestions::RangeTotal(), gracenote::metadata::GnResponseVideoObjects::RangeTotal(), gracenote::metadata::GnResponseContributors::RangeTotal(), gracenote::metadata::GnResponseVideoSeries::RangeTotal(), gracenote::metadata::GnResponseVideoSeasons::RangeTotal(), gracenote::metadata::GnResponseVideoWork::RangeTotal(), gracenote::metadata::GnResponseVideoProduct::RangeTotal(), gracenote::metadata::GnVideoCredit::Rank(), gracenote::metadata::GnRating::Rating(), gracenote::metadata::GnRating::RatingBBFC(), gracenote::metadata::GnRating::RatingCanadianTV(), gracenote::metadata::GnRating::RatingCBFC(), gracenote::metadata::GnRating::RatingCHVRS(), gracenote::metadata::GnRating::RatingDesc(), gracenote::metadata::GnRating::RatingDJTCQ(), gracenote::metadata::GnRating::RatingDVDParental(), gracenote::metadata::GnRating::RatingEIRIN(), gracenote::metadata::GnRating::RatingFAB(), gracenote::metadata::GnRating::RatingFinnish(), gracenote::metadata::GnRating::RatingFrance(), gracenote::metadata::GnRating::RatingFSK(), gracenote::metadata::GnRating::RatingHongKong(), gracenote::metadata::GnRating::RatingINCAA(), gracenote::metadata::GnRating::RatingItaly(), gracenote::metadata::GnRating::RatingKMRB(), gracenote::metadata::GnRating::RatingMPAA(), gracenote::metadata::GnRating::RatingMPAATV(), gracenote::metadata::GnRating::RatingOFLC(), gracenote::metadata::GnRating::RatingQuebec(), gracenote::metadata::GnRating::RatingReason(), gracenote::metadata::GnRating::RatingSpain(), gracenote::metadata::GnRating::RatingType(), gracenote::metadata::GnRating::RatingTypeId(), gracenote::metadata::GnVideoLayer::RegionCode(), gracenote::metadata::GnVideoSeason::Reputation(), gracenote::metadata::GnVideoSeries::Reputation(), gracenote::metadata::GnVideoWork::Reputation(), gracenote::metadata::GnResponseTracks::ResultCount(), gracenote::metadata::GnResponseAlbums::ResultCount(), gracenote::metadata::GnResponseDataMatches::ResultCount(), gracenote::metadata::GnResponseVideoSuggestions::ResultCount(), gracenote::metadata::GnResponseVideoObjects::ResultCount(), gracenote::metadata::GnResponseContributors::ResultCount(), gracenote::metadata::GnResponseVideoSeries::ResultCount(), gracenote::metadata::GnResponseVideoSeasons::ResultCount(), gracenote::metadata::GnResponseVideoWork::ResultCount(), gracenote::metadata::GnResponseVideoProduct::ResultCount(), gracenote::metadata::GnVideoCredit::Role(), gracenote::metadata::GnRole::Role(), gracenote::metadata::GnVideoCredit::RoleBilling(), gracenote::metadata::GnVideoCredit::RoleId(), gracenote::metadata::GnVideoSeason::Scenario(), gracenote::metadata::GnVideoSeries::Scenario(), gracenote::metadata::GnVideoWork::Scenario(), gracenote::metadata::GnAlbum::Script(), gracenote::metadata::GnVideoSeason::SeasonCount(), gracenote::metadata::GnVideoWork::SeasonCount(), gracenote::metadata::GnVideoWork::SeasonEpisode(), gracenote::metadata::GnVideoWork::SeasonEpisodeCount(), gracenote::metadata::GnVideoSeason::SeasonNumber(), gracenote::metadata::GnVideoWork::SeasonNumber(), gracenote::metadata::GnVideoSeason::SerialType(), gracenote::metadata::GnVideoSeries::SerialType(), gracenote::metadata::GnVideoWork::SerialType(), gracenote::metadata::GnVideoWork::SeriesEpisode(), gracenote::metadata::GnVideoWork::SeriesEpisodeCount(), gracenote::metadata::GnVideoSeason::SettingEnvironment(), gracenote::metadata::GnVideoSeries::SettingEnvironment(), gracenote::metadata::GnVideoWork::SettingEnvironment(), gracenote::metadata::GnVideoSeason::SettingTimePeriod(), gracenote::metadata::GnVideoSeries::SettingTimePeriod(), gracenote::metadata::GnVideoWork::SettingTimePeriod(), gracenote::metadata::GnAsset::Size(), gracenote::metadata::GnName::Sortable(), gracenote::metadata::GnTitle::Sortable(), gracenote::metadata::GnName::SortableScheme(), gracenote::metadata::GnTitle::SortableScheme(), gracenote::metadata::GnExternalId::Source(), gracenote::metadata::GnVideoSeason::Source(), gracenote::metadata::GnVideoSeries::Source(), gracenote::metadata::GnVideoWork::Source(), gracenote::metadata::GnVideoSeason::StoryType(), gracenote::metadata::GnVideoSeries::StoryType(), gracenote::metadata::GnVideoWork::StoryType(), gracenote::metadata::GnVideoSeason::Style(), gracenote::metadata::GnVideoSeries::Style(), gracenote::metadata::GnVideoWork::Style(), gracenote::metadata::GnResponseVideoSuggestions::SuggestionText(), gracenote::metadata::GnResponseVideoSuggestions::SuggestionTitle(), gracenote::metadata::GnResponseVideoSuggestions::SuggestionType(), gracenote::metadata::GnAudioWork::TagId(), gracenote::metadata::GnTrack::TagId(), gracenote::metadata::GnAlbum::TagId(), gracenote::playlist::GnPlaylistAttributes::Tempo(), gracenote::metadata::GnTrack::Tempo(), gracenote::metadata::GnVideoSeason::Topic(), gracenote::metadata::GnVideoSeries::Topic(), gracenote::metadata::GnVideoWork::Topic(), gracenote::metadata::GnAlbum::TotalInSet(), gracenote::metadata::GnAlbum::TrackCount(), gracenote::metadata::GnAlbum::TrackMatchNumber(), gracenote::metadata::GnTrack::TrackNumber(), gracenote::metadata::GnMatch::Tui(), gracenote::metadata::GnAudioWork::Tui(), gracenote::metadata::GnTrack::Tui(), gracenote::metadata::GnVideoSeason::Tui(), gracenote::metadata::GnAlbum::Tui(), gracenote::metadata::GnContributor::Tui(), gracenote::metadata::GnVideoSeries::Tui(), gracenote::metadata::GnVideoWork::Tui(), gracenote::metadata::GnVideoDisc::Tui(), gracenote::metadata::GnVideoProduct::Tui(), gracenote::metadata::GnVideoWork::TuiMatchProduct(), gracenote::metadata::GnMatch::TuiTag(), gracenote::metadata::GnAudioWork::TuiTag(), gracenote::metadata::GnTrack::TuiTag(), gracenote::metadata::GnVideoSeason::TuiTag(), gracenote::metadata::GnAlbum::TuiTag(), gracenote::metadata::GnContributor::TuiTag(), gracenote::metadata::GnVideoSeries::TuiTag(), gracenote::metadata::GnVideoWork::TuiTag(), gracenote::metadata::GnVideoDisc::TuiTag(), gracenote::metadata::GnVideoProduct::TuiTag(), gracenote::metadata::GnVideoLayer::TvSystem(), gracenote::metadata::GnExternalId::Type(), gracenote::metadata::GnAsset::Url(), gracenote::metadata::GnExternalId::Value(), gracenote::metadata::GnVideoFeature::VideoFeatureType(), gracenote::metadata::GnVideoSeason::VideoMood(), gracenote::metadata::GnVideoSeries::VideoMood(), gracenote::metadata::GnVideoWork::VideoMood(), gracenote::metadata::GnVideoSeason::VideoProductionType(), gracenote::metadata::GnVideoSeries::VideoProductionType(), gracenote::metadata::GnVideoWork::VideoProductionType(), gracenote::metadata::GnVideoFeature::VideoProductionType(), gracenote::metadata::GnVideoProduct::VideoProductionType(), gracenote::metadata::GnVideoSeason::VideoProductionTypeId(), gracenote::metadata::GnVideoSeries::VideoProductionTypeId(), gracenote::metadata::GnVideoWork::VideoProductionTypeId(), gracenote::metadata::GnVideoFeature::VideoProductionTypeId(), gracenote::metadata::GnVideoProduct::VideoProductionTypeId(), gracenote::metadata::GnVideoLayer::VideoRegion(), gracenote::metadata::GnVideoProduct::VideoRegion(), gracenote::metadata::GnVideoLayer::VideoRegionDesc(), gracenote::metadata::GnVideoProduct::VideoRegionDesc(), gracenote::metadata::GnVideoSeason::WorkType(), gracenote::metadata::GnVideoSeries::WorkType(), gracenote::metadata::GnVideoWork::WorkType(), gracenote::metadata::GnTrack::Year(), and gracenote::metadata::GnAlbum::Year().
gnsdk_uint32_t gracenote::metadata::GnDataObject::StringValueCount (gnsdk_cstr_t valueKey) const inline
Returns count of the metadata values available for the key.
Parameters
valueKey [in] Key of the value count to return
Returns
count
Referenced by gracenote::metadata::gn_gdo_string_provider::count().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.