GNSDK for Desktop: gracenote::musicid_file::GnMusicIdFileInfoManager Class Reference
gracenote::musicid_file::GnMusicIdFileInfoManager Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE
GnMusicIdFileInfo Add (gnsdk_cstr_t uniqueIdentifier, IGnMusicIdFileInfoEvents *pEventHandler=GNSDK_NULL) throw (GnError)
gnsdk_uint32_t AddFromXml (gnsdk_cstr_t xmlStr) throw (GnError)
GnMusicIdFileInfo at (gnsdk_uint32_t index) const
musicid_file_info_iterator begin () const
gnsdk_uint32_t count () const
musicid_file_info_iterator end () const
GnMusicIdFileInfo GetByFilename (gnsdk_cstr_t filename) throw (GnError)
GnMusicIdFileInfo GetByFolder (gnsdk_cstr_t folder, gnsdk_uint32_t index) throw (GnError)
GnMusicIdFileInfo GetByIdentifier (gnsdk_cstr_t ident) throw (GnError)
GnMusicIdFileInfo operator[] (gnsdk_uint32_t index) const
void Remove (const GnMusicIdFileInfo &fileInfo) throw (GnError)
GnString RenderToXml () throw (GnError)
Friends
class GnMusicIdFile
Detailed Description
Provides services for adding audio tracks to GnMusicIdFile for identification.
Member Function Documentation
GNWRAPPER_ANNOTATE GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::Add (gnsdk_cstr_t uniqueIdentifier, IGnMusicIdFileInfoEvents * pEventHandler = GNSDK_NULL) throw (GnError)
Add an audio file to GnMusicIdFile for identification
Parameters
uniqueIdentifier [in] Unique identifier for the audio track, such as a filename or library reference
pEventHandler [in-opt] Event delegate for processing events specifically for this audio file. Use where the generic event handler provided on GnMusicIdFile construction isn't suitable
Returns
Object representing the audio file
gnsdk_uint32_t gracenote::musicid_file::GnMusicIdFileInfoManager::AddFromXml (gnsdk_cstr_t xmlStr) throw (GnError)
Add audio file(s) represented by an XML string to GnMusicIdFile for identification
Parameters
xmlStr [in] Audio file(s) XML string, such as one created using RenderToXml()
Returns
Number of audio files added
GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::at (gnsdk_uint32_t index) const inline
Get audio file at specified index
Parameters
index [in] Audio file index
Returns
file iterator
References gracenote::musicid_file::musicid_file_info_provider::get_data().
musicid_file_info_iterator gracenote::musicid_file::GnMusicIdFileInfoManager::begin () const inline
Get an audio file iterator set at the first audio file.
Returns
audio file iterator
gnsdk_uint32_t gracenote::musicid_file::GnMusicIdFileInfoManager::count () const inline
Get number of audio files added
Returns
Number of audio files
References gracenote::musicid_file::musicid_file_info_provider::count().
musicid_file_info_iterator gracenote::musicid_file::GnMusicIdFileInfoManager::end () const inline
Get an audio file iterator set at the last audio file.
Returns
audio file iterator
GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::GetByFilename (gnsdk_cstr_t filename) throw (GnError)
Retrieves the GnMusicIdFileInfo object that matches the given file name.
Parameters
filename [in] File name or other string identifier of FileInfo to retrieve
Remarks:
Only GnMusicIdFileInfo objects that have file name information set through GnMusicIdFile::FileName can be retrieved with this function.
Note:
GnMusicIdFile does not enforce unique GnMusucIdFileInfo file names. Consequently, to use this function well, it is important to give unique file names to each GnMusicIdFileInfo added (such as the full path and file name). GnMusicIdFile does not check if the given file name given is a valid path or file name, nor is it required to be one. GnMusicIdFile only performs a match against the existing GnMusicIdFileInfo path and file names.
GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::GetByFolder (gnsdk_cstr_t folder, gnsdk_uint32_t index) throw (GnError)
Retrieves the index'th GnMusicIdFileInfo object matching the given folder.
Parameters
folder [in] Folder name of GnMusicIdFileInfo object to retrieve
index [in] Index of GnMusicIdFileInfo object in folder name to retrieve
Remarks:
Only a GnMusicIdFileInfo that has path information set through GnMusicIdFile::FileName can be retrieved with this function. GnMusicId does not check if the given folder name is a valid path, nor is it required to be one. GnMusicIdFile only performs a match against existing GnMusiucIdFileInfo folder names.
GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::GetByIdentifier (gnsdk_cstr_t ident) throw (GnError)
Retrieves the GnMusicIdFileInfo object that matches the given identifier string and is associated with the given MusicID-File handle.
Parameters
ident [in] String identifier of FileInfo to retrieve
Remarks:
The string identifier of each GnMusicIdFileInfo is set when Add is called. GnMusicIdFile enforces GnMusicIdFileInfo identifiers to be unique.
GnMusicIdFileInfo gracenote::musicid_file::GnMusicIdFileInfoManager::operator[] (gnsdk_uint32_t index) const inline
Get audio file at specified index
Parameters
index [in] Audio file index
Returns
Object representing audio file
References gracenote::musicid_file::musicid_file_info_provider::get_data().
void gracenote::musicid_file::GnMusicIdFileInfoManager::Remove (const GnMusicIdFileInfo & fileInfo) throw (GnError)
Remove and audio file from GnMusicIdFile
Parameters
fileInfo [in] Object representing audio file to remove
GnString gracenote::musicid_file::GnMusicIdFileInfoManager::RenderToXml () throw (GnError)
Render all added audio files to an XML string
Returns
XML string
Friends And Related Function Documentation
friend class GnMusicIdFile friend
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:52.