GNSDK for Desktop: gracenote::metadata::GnVideoSide Class Reference
gracenote::metadata::GnVideoSide Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnVideoSide ()
GnVideoSide (gnsdk_gdo_handle_t gdoHandle)
virtual ~GnVideoSide ()
layer_iterable Layers () const
bool Matched () const
gnsdk_cstr_t Notes () const
GnTitle OfficialTitle () const
gnsdk_uint32_t Ordinal () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Both DVDs and Blu-ray discs can be dual side. Double-Sided discs include a single layer on each side of the disc that data can be recorded to. Double-Sided recordable DVDs come in two formats: DVD-R and DVD+R, including the rewritable DVD-RW and DVD+RW. These discs can hold about 8.75GB of data if you burn to both sides. Dual-side Blu-ray discs can store 50 GB of data (25GB on each side).
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoSide::GnVideoSide () inline
gracenote::metadata::GnVideoSide::GnVideoSide (gnsdk_gdo_handle_t gdoHandle) inline
virtual gracenote::metadata::GnVideoSide::~GnVideoSide () inline virtual
Member Function Documentation
layer_iterable gracenote::metadata::GnVideoSide::Layers () const inline
Iterator for video layers
Remarks:
The ordinal parameter specifies the n'th child video layer to retrieve.
bool gracenote::metadata::GnVideoSide::Matched () const inline
Matched boolean value indicating whether this type is the one that matched the input criteria.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSide::Notes () const inline
Notes
References gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoSide::OfficialTitle () const inline
Official title object
gnsdk_uint32_t gracenote::metadata::GnVideoSide::Ordinal () const inline
Ordinal value
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.