GNSDK for Desktop: gracenote::metadata::GnVideoSeason Class Reference
gracenote::metadata::GnVideoSeason Class Reference
Public Member Functions
GnVideoSeason ()
GnVideoSeason (gnsdk_gdo_handle_t gdoHandle)
GnVideoSeason (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnVideoSeason ()
gnsdk_cstr_t Audience () const
content_iterable Contents () const
gnsdk_cstr_t DateOriginalRelease () const
gnsdk_uint32_t Duration () const
gnsdk_cstr_t DurationUnits () const
externalid_iterable ExternalIds () const
gnsdk_uint32_t FranchiseCount () const
gnsdk_uint32_t FranchiseNum () const
GnTitle FranchiseTitle () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnVideoSeason, GNSDK_GDO_TYPE_VIDEO_SEASON)
gnsdk_cstr_t GnUId () const
bool IsFullResult () const
GnTitle OfficialTitle () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_cstr_t PlotSynopsis () const
gnsdk_cstr_t PlotSynopsisLanguage () const
gnsdk_cstr_t PlotTagline () const
gnsdk_cstr_t ProductId () const
product_iterable Products () const
GnRating Rating () const
gnsdk_cstr_t Reputation () const
gnsdk_cstr_t Scenario () const
gnsdk_uint32_t SeasonCount () const
gnsdk_uint32_t SeasonNumber () const
gnsdk_cstr_t SerialType () const
series_iterable Series () const
gnsdk_cstr_t SettingEnvironment () const
gnsdk_cstr_t SettingTimePeriod () const
gnsdk_cstr_t Source () const
gnsdk_cstr_t StoryType () const
gnsdk_cstr_t Style () const
gnsdk_cstr_t Topic () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
video_credit_iterable VideoCredits () const
gnsdk_cstr_t VideoMood () const
gnsdk_cstr_t VideoProductionType () const
gnsdk_uint32_t VideoProductionTypeId () const
works_iterable Works () const
gnsdk_cstr_t WorkType () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Constructor & Destructor Documentation
gracenote::metadata::GnVideoSeason::GnVideoSeason () inline
gracenote::metadata::GnVideoSeason::GnVideoSeason (gnsdk_gdo_handle_t gdoHandle) inline
gracenote::metadata::GnVideoSeason::GnVideoSeason (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
virtual gracenote::metadata::GnVideoSeason::~GnVideoSeason () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Audience () const inline
Target audience, e.g., "Kids and Family"
References gracenote::metadata::GnDataObject::StringValue().
content_iterable gracenote::metadata::GnVideoSeason::Contents () const inline
Iterator for the content (cover art, biography, etc.) associated with this video work.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::DateOriginalRelease () const inline
Video season's original release date.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::Duration () const inline
Duration in seconds such as "3600" for a 60-minute program.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::DurationUnits () const inline
Duration units value (seconds, "SEC").
References gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnVideoSeason::ExternalIds () const inline
Iterator for extended IDs, which identify a source external to Gracenote (e.g., NetFlix), that also have an identifier for this work. Extended ID type supports Link data.
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::FranchiseCount () const inline
Franchise count.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::FranchiseNum () const inline
Franchise number.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoSeason::FranchiseTitle () const inline
Franchise title object.
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Genre (GnDataLevel level) const inline
Genre. This is a list/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that the list or locale be loaded into memory through a successful allocation of a GnLocale object
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. The SDK returns a LocaleNotLoaded message when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::GnId () const inline
Video season's Gracenote identifier.
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnVideoSeason::GNSDK_CHECKED_CAST (GnVideoSeason , GNSDK_GDO_TYPE_VIDEO_SEASON)
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::GnUId () const inline
Video season's Gracenote unique identifier.
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnVideoSeason::IsFullResult () const inline
Flag indicating if response result contains full (true) or partial metadata.
Note:
What constitutes a full result varies among response results, and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnVideoSeason::OfficialTitle () const inline
Official title object
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Origin (GnDataLevel level) const inline
Origin, e.g., "New York City." List/locale dependent, multi-level field.
Remarks:
This is a list-based value requiring that the list or locale be loaded into memory through a successful allocation of a GnLocale object
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. The SDK returns a LocaleNotLoaded message when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::PlotSynopsis () const inline
Plot sypnosis, e.g., for Friends episode:."Monica's popularity at a karaoke club might have more to do with her revealing dress than her voice"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::PlotSynopsisLanguage () const inline
Plot sypnosis language, e.g., English
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::PlotTagline () const inline
Plot tagline, e.g., "An adventure as big as life itself."
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::ProductId () const inline
Video season's product ID (aka Tag ID).
Remarks:
Available for most types, this value can be stored or transmitted. Can be used as a static identifier for the current content as it will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
product_iterable gracenote::metadata::GnVideoSeason::Products () const inline
Iterator for child products
GnRating gracenote::metadata::GnVideoSeason::Rating () const inline
Rating object.
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Reputation () const inline
Reputation, e.g., "Chick flick".
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Scenario () const inline
Scenario, e.g., Action
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::SeasonCount () const inline
Season count - total number of seasons.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::SeasonNumber () const inline
Season number.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::SerialType () const inline
Serial type, e.g., Series or Episode
References gracenote::metadata::GnDataObject::StringValue().
series_iterable gracenote::metadata::GnVideoSeason::Series () const inline
Iterator for child series'
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::SettingEnvironment () const inline
Setting environment, e.g., "High School"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::SettingTimePeriod () const inline
Setting time period, e.g., "Jazz Age 1919-1929".
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Source () const inline
Source, e.g., "Fairy Tales and Nursery Rhymes"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::StoryType () const inline
Overall story type, e.g., "Love Story".
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Style () const inline
Style, e.g., "Film Noir"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Topic () const inline
Topic value, e.g., "Teen Angst"
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::Tui () const inline
Video season's TUI (title-unique identifier).
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::TuiTag () const inline
Video season's Tui Tag.
References gracenote::metadata::GnDataObject::StringValue().
video_credit_iterable gracenote::metadata::GnVideoSeason::VideoCredits () const inline
Iterable for child credits. For music types, this includes all credits except the artist credit.
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::VideoMood () const inline
Video mood, e.g., Playful.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::VideoProductionType () const inline
Video production type, e.g., Animation. This is a list/locale dependent value.
Remarks:
This is a list-based value requiring that the list or locale be loaded into memory through a successful allocation of a GnLocale object
To render locale-dependent information for list-based values, the application must allocate a GnLocale object. The SDK returns a LocaleNotLoaded message when locale information is not set prior to a request for a list-based value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnVideoSeason::VideoProductionTypeId () const inline
Video production type identifier.
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
works_iterable gracenote::metadata::GnVideoSeason::Works () const inline
Iterator for child works.
gnsdk_cstr_t gracenote::metadata::GnVideoSeason::WorkType () const inline
Work type, e.g., Musical
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:51.