GNSDK for Desktop: gracenote::gnstd Class Reference
gracenote::gnstd Class Reference
Static Public Member Functions
static gnsdk_int32_t gn_atoi (gnsdk_cstr_t value)
static bool gn_itoa (char *buffer, gnsdk_size_t buffer_sz, int value)
static gnsdk_int32_t gn_strcmp (gnsdk_cstr_t lhs, gnsdk_cstr_t rhs)
static gnsdk_size_t gn_strcpy (char *dest, gnsdk_size_t dest_size, gnsdk_cstr_t src)
static gnsdk_size_t gn_strlen (gnsdk_cstr_t s)
static bool gn_strtobool (gnsdk_cstr_t value)
Static Public Attributes
static const char * kEmptyString
Member Function Documentation
static gnsdk_int32_t gracenote::gnstd::gn_atoi (gnsdk_cstr_t value) static
Referenced by gracenote::metadata::GnAsset::Bytes(), gracenote::metadata::GnTrack::CurrentPosition(), gracenote::metadata::GnAlbum::DiscInSet(), gracenote::metadata::GnTrack::Duration(), gracenote::metadata::GnVideoChapter::Duration(), gracenote::metadata::GnVideoSeason::Duration(), gracenote::metadata::GnVideoSeries::Duration(), gracenote::metadata::GnVideoWork::Duration(), gracenote::metadata::GnVideoFeature::Duration(), gracenote::metadata::GnVideoProduct::Duration(), gracenote::metadata::GnVideoSeason::FranchiseCount(), gracenote::metadata::GnVideoSeries::FranchiseCount(), gracenote::metadata::GnVideoWork::FranchiseCount(), gracenote::metadata::GnVideoSeason::FranchiseNum(), gracenote::metadata::GnVideoSeries::FranchiseNum(), gracenote::metadata::GnVideoWork::FranchiseNum(), gracenote::metadata::GnTrack::MatchDuration(), gracenote::metadata::GnTrack::MatchPosition(), gracenote::metadata::GnTrack::MatchScore(), gracenote::metadata::GnAlbum::MatchScore(), gracenote::metadata::GnVideoChapter::Ordinal(), gracenote::metadata::GnVideoFeature::Ordinal(), gracenote::metadata::GnVideoLayer::Ordinal(), gracenote::metadata::GnVideoSide::Ordinal(), gracenote::metadata::GnVideoDisc::Ordinal(), gracenote::metadata::GnResponseTracks::RangeEnd(), gracenote::metadata::GnResponseAlbums::RangeEnd(), gracenote::metadata::GnResponseDataMatches::RangeEnd(), gracenote::metadata::GnResponseVideoSuggestions::RangeEnd(), gracenote::metadata::GnResponseVideoObjects::RangeEnd(), gracenote::metadata::GnResponseContributors::RangeEnd(), gracenote::metadata::GnResponseVideoSeries::RangeEnd(), gracenote::metadata::GnResponseVideoSeasons::RangeEnd(), gracenote::metadata::GnResponseVideoWork::RangeEnd(), gracenote::metadata::GnResponseVideoProduct::RangeEnd(), gracenote::metadata::GnResponseTracks::RangeStart(), gracenote::metadata::GnResponseAlbums::RangeStart(), gracenote::metadata::GnResponseDataMatches::RangeStart(), gracenote::metadata::GnResponseVideoSuggestions::RangeStart(), gracenote::metadata::GnResponseVideoObjects::RangeStart(), gracenote::metadata::GnResponseContributors::RangeStart(), gracenote::metadata::GnResponseVideoSeries::RangeStart(), gracenote::metadata::GnResponseVideoSeasons::RangeStart(), gracenote::metadata::GnResponseVideoWork::RangeStart(), gracenote::metadata::GnResponseVideoProduct::RangeStart(), gracenote::metadata::GnResponseTracks::RangeTotal(), gracenote::metadata::GnResponseAlbums::RangeTotal(), gracenote::metadata::GnResponseDataMatches::RangeTotal(), gracenote::metadata::GnResponseVideoSuggestions::RangeTotal(), gracenote::metadata::GnResponseVideoObjects::RangeTotal(), gracenote::metadata::GnResponseContributors::RangeTotal(), gracenote::metadata::GnResponseVideoSeries::RangeTotal(), gracenote::metadata::GnResponseVideoSeasons::RangeTotal(), gracenote::metadata::GnResponseVideoWork::RangeTotal(), gracenote::metadata::GnResponseVideoProduct::RangeTotal(), gracenote::metadata::GnVideoCredit::Rank(), gracenote::metadata::GnRating::RatingTypeId(), gracenote::metadata::GnResponseTracks::ResultCount(), gracenote::metadata::GnResponseAlbums::ResultCount(), gracenote::metadata::GnResponseDataMatches::ResultCount(), gracenote::metadata::GnResponseVideoSuggestions::ResultCount(), gracenote::metadata::GnResponseVideoObjects::ResultCount(), gracenote::metadata::GnResponseContributors::ResultCount(), gracenote::metadata::GnResponseVideoSeries::ResultCount(), gracenote::metadata::GnResponseVideoSeasons::ResultCount(), gracenote::metadata::GnResponseVideoWork::ResultCount(), gracenote::metadata::GnResponseVideoProduct::ResultCount(), gracenote::metadata::GnVideoCredit::RoleId(), gracenote::metadata::GnVideoSeason::SeasonCount(), gracenote::metadata::GnVideoWork::SeasonCount(), gracenote::metadata::GnVideoWork::SeasonEpisode(), gracenote::metadata::GnVideoWork::SeasonEpisodeCount(), gracenote::metadata::GnVideoSeason::SeasonNumber(), gracenote::metadata::GnVideoWork::SeasonNumber(), gracenote::metadata::GnVideoWork::SeriesEpisode(), gracenote::metadata::GnVideoWork::SeriesEpisodeCount(), gracenote::metadata::GnAlbum::TotalInSet(), gracenote::metadata::GnAlbum::TrackCount(), gracenote::metadata::GnAlbum::TrackMatchNumber(), gracenote::metadata::GnVideoSeason::VideoProductionTypeId(), gracenote::metadata::GnVideoSeries::VideoProductionTypeId(), gracenote::metadata::GnVideoWork::VideoProductionTypeId(), gracenote::metadata::GnVideoFeature::VideoProductionTypeId(), and gracenote::metadata::GnVideoProduct::VideoProductionTypeId().
static bool gracenote::gnstd::gn_itoa (char * buffer, gnsdk_size_t buffer_sz, int value) static
static gnsdk_int32_t gracenote::gnstd::gn_strcmp (gnsdk_cstr_t lhs, gnsdk_cstr_t rhs) static
Referenced by gracenote::gnconvert::_convertDescriptorCCpp(), gracenote::gnconvert::_convertLanguageCCpp(), gracenote::gnconvert::_convertRegionCCpp(), gracenote::metadata::GnContent::ContentType(), gracenote::metadata::GnDataMatch::IsAlbum(), gracenote::metadata::GnDataMatch::IsContributor(), gracenote::gn_facade_range_iterator< gnsdk_cstr_t, _Provider >::operator==(), and gracenote::metadata::GnAsset::Size().
static gnsdk_size_t gracenote::gnstd::gn_strcpy (char * dest, gnsdk_size_t dest_size, gnsdk_cstr_t src) static
static gnsdk_size_t gracenote::gnstd::gn_strlen (gnsdk_cstr_t s) static
static bool gracenote::gnstd::gn_strtobool (gnsdk_cstr_t value) static
Referenced by gracenote::metadata::GnContributor::CollaboratorResult(), gracenote::metadata::GnAlbum::IsClassical(), gracenote::metadata::GnTrack::IsFullResult(), gracenote::metadata::GnVideoSeason::IsFullResult(), gracenote::metadata::GnAlbum::IsFullResult(), gracenote::metadata::GnContributor::IsFullResult(), gracenote::metadata::GnVideoSeries::IsFullResult(), gracenote::metadata::GnVideoWork::IsFullResult(), gracenote::metadata::GnVideoProduct::IsFullResult(), gracenote::metadata::GnTrack::Matched(), gracenote::metadata::GnVideoFeature::Matched(), gracenote::metadata::GnVideoLayer::Matched(), gracenote::metadata::GnVideoSide::Matched(), gracenote::metadata::GnVideoDisc::Matched(), gracenote::metadata::GnResponseTracks::NeedsDecision(), gracenote::metadata::GnResponseAlbums::NeedsDecision(), gracenote::metadata::GnResponseDataMatches::NeedsDecision(), gracenote::metadata::GnResponseVideoSuggestions::NeedsDecision(), gracenote::metadata::GnResponseVideoObjects::NeedsDecision(), gracenote::metadata::GnResponseContributors::NeedsDecision(), gracenote::metadata::GnResponseVideoSeries::NeedsDecision(), gracenote::metadata::GnResponseVideoSeasons::NeedsDecision(), gracenote::metadata::GnResponseVideoWork::NeedsDecision(), and gracenote::metadata::GnResponseVideoProduct::NeedsDecision().
Member Data Documentation
const char* gracenote::gnstd::kEmptyString static
Referenced by gracenote::metadata::GnDataObject::GetType(), gracenote::gn_facade_range_iterator< gnsdk_cstr_t, _Provider >::operator=(), and gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:49.