GNSDK for Desktop: gracenote::metadata::GnAlbum Class Reference
gracenote::metadata::GnAlbum Class Reference
Public Member Functions
GnAlbum ()
GnAlbum (gnsdk_gdo_handle_t gdoHandle)
GnAlbum (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnAlbum ()
GnArtist Artist () const
gnsdk_cstr_t Compilation () const
GnContent Content (GnContentType contentType) const
content_iterable Contents () const
GnContent CoverArt () const
credit_iterable Credits () const
gnsdk_uint32_t DiscInSet () const
externalid_iterable ExternalIds () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GlobalId () const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnAlbum, GNSDK_GDO_TYPE_ALBUM)
gnsdk_cstr_t GnUId () const
bool IsClassical () const
bool IsFullResult () const
gnsdk_cstr_t Label () const
gnsdk_cstr_t Language () const
gnsdk_cstr_t LanguageCode () const
gnsdk_uint32_t MatchScore () const
GnContent Review () const
gnsdk_cstr_t Script () const
gnsdk_cstr_t TagId () const
GnTitle Title () const
GnTitle TitleClassical () const
GnTitle TitleRegional () const
GnTitle TitleRegionalLocale () const
gnsdk_uint32_t TotalInSet () const
GnTrack Track (gnsdk_uint32_t trackNumber) const
gnsdk_uint32_t TrackCount () const
GnTrack TrackMatched (gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t TrackMatchNumber (gnsdk_uint32_t ordinal=1) const
track_iterable Tracks () const
track_iterable TracksMatched () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
gnsdk_cstr_t Year () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Collection of audio recordings. Provides access to album cover art when received from a query object with content enabled in lookup data.
Constructor & Destructor Documentation
gracenote::metadata::GnAlbum::GnAlbum () inline
Constructs empty GnAlbum object
gracenote::metadata::GnAlbum::GnAlbum (gnsdk_gdo_handle_t gdoHandle) inline
Constructs a GnAlbum object from a native handle
Parameters
gdoHandle [in] Native handle
gracenote::metadata::GnAlbum::GnAlbum (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
Constructs a GnAlbum object from identifier and identifier tag
Parameters
id [in] Identifier
idTag [in] Identifier tag
virtual gracenote::metadata::GnAlbum::~GnAlbum () inline virtual
Member Function Documentation
GnArtist gracenote::metadata::GnAlbum::Artist () const inline
Album's artist.
Returns
Artist
gnsdk_cstr_t gracenote::metadata::GnAlbum::Compilation () const inline
Album's compilation value
Returns
Compilation
References gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnAlbum::Content (GnContentType contentType) const inline
Content (cover art, biography, review, etc.) object
Parameters
GnContentType object
Returns
Content object
References gracenote::gnconvert::_convertContentTypeCppC().
content_iterable gracenote::metadata::GnAlbum::Contents () const inline
Iterator for the content associated with this contributor.
Returns
Iterator
GnContent gracenote::metadata::GnAlbum::CoverArt () const inline
Fetch the album's cover art content object
Returns
Content object
credit_iterable gracenote::metadata::GnAlbum::Credits () const inline
Iterator for accessing album credits, except artist credit, which is accessed with another dedicated method The Artist Credit is accessed via a dedicated method.
Returns
Iterator
gnsdk_uint32_t gracenote::metadata::GnAlbum::DiscInSet () const inline
Album's volume number in a multi-volume set. This value is not always available.
Returns
Disc in set
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnAlbum::ExternalIds () const inline
Iterator for album's external identifiers, e.g., Amazon's identifier.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnAlbum::Genre (GnDataLevel level) const inline
Album's genre, e.g., punk rock. List/locale dependent, multi-level field.
Parameters
level [in] Data level
Returns
Genre
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::GlobalId () const inline
Album's global identifier (used for transcriptions).
Returns
Gracenote Global identifier
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::GnId () const inline
Album's Gracenote identifier.
Returns
Gracenote identifier
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnAlbum::GNSDK_CHECKED_CAST (GnAlbum , GNSDK_GDO_TYPE_ALBUM)
gnsdk_cstr_t gracenote::metadata::GnAlbum::GnUId () const inline
Album's Gracenote unique identifier.
Returns
Gracenote unique identifier
References gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnAlbum::IsClassical () const inline
Flag indicating if enhanced classical music data exists for this album.
Returns
True is this is a classical album, false otherwise
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
bool gracenote::metadata::GnAlbum::IsFullResult () const inline
Flag indicating if response contains full (true) or partial (false) metadata.
Returns
True if full result, false if partial result
Note:
What constitutes a full result varies among the individual response types and results, and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::Label () const inline
Album's label - record company that released the album, e.g., Atlantic. Album label values are not always available.
Returns
Label
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::Language (void) const inline
Display language
Returns
Language string
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::LanguageCode () const inline
Display langauge's 3-letter ISO code
Returns
Language code
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_uint32_t gracenote::metadata::GnAlbum::MatchScore () const inline
Match confidence score for top-level match
Returns
Match score
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnAlbum::Review () const inline
Fetch the album's review content object
Returns
Content object
gnsdk_cstr_t gracenote::metadata::GnAlbum::Script () const inline
Script used by the display values as ISO 15924 code
Returns
Script value.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::TagId () const inline
Album's Gracenote Tag identifier (Tag ID is same as Product ID)
Returns
Gracenote Tag identifier
Remarks:
This method exists primarily to support legacy implementations. We recommend using the Product ID method to retrieve product related identifiers
References gracenote::metadata::GnDataObject::StringValue().
GnTitle gracenote::metadata::GnAlbum::Title () const inline
Album's official title.
Returns
Title
GnTitle gracenote::metadata::GnAlbum::TitleClassical () const inline
Title presented using Gracenote's Three Line Solution for classical track (composer/work title/movement title)
Returns
Title
GnTitle gracenote::metadata::GnAlbum::TitleRegional () const inline
Regional title - list/locale dependent field
Returns
Title
GnTitle gracenote::metadata::GnAlbum::TitleRegionalLocale () const inline
Regional locale title - list/locale dependent field
Returns
Title
gnsdk_uint32_t gracenote::metadata::GnAlbum::TotalInSet () const inline
Total number of volumes in album's multi-volume set. This value is not always available.
Returns
Total in set
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTrack gracenote::metadata::GnAlbum::Track (gnsdk_uint32_t trackNumber) const inline
Album track using the track number.
Parameters
trackNumber Ordinal of the desired track (1-based)
Returns
Track
gnsdk_uint32_t gracenote::metadata::GnAlbum::TrackCount () const inline
Total number of tracks on this album.
Returns
Count
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
GnTrack gracenote::metadata::GnAlbum::TrackMatched (gnsdk_uint32_t ordinal = 1) const inline
Ordinal value on album for matching track
Parameters
ordinal Ordinal of the desired track (1-based)
Returns
Track
gnsdk_uint32_t gracenote::metadata::GnAlbum::TrackMatchNumber (gnsdk_uint32_t ordinal = 1) const inline
Track number on album for matching track
Parameters
ordinal Ordinal of the desired track (1-based)
Returns
Matched number
References gracenote::gnstd::gn_atoi(), and gracenote::metadata::GnDataObject::StringValue().
track_iterable gracenote::metadata::GnAlbum::Tracks () const inline
Iterator for accessing album tracks
Returns
Iterator
track_iterable gracenote::metadata::GnAlbum::TracksMatched () const inline
Iterator for accessing album's matched track(s).
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnAlbum::Tui () const inline
Album's Gracenote Tui (title-unique identifier)
Returns
Tui
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::TuiTag () const inline
Album's Gracenote Tui Tag
Returns
Tui Tag
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnAlbum::Year () const inline
Year the album was released.
Returns
year
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.