GNSDK for Desktop: gracenote::metadata::GnContent Class Reference
gracenote::metadata::GnContent Class Reference
Public Member Functions
GNWRAPPER_ANNOTATE GnContent ()
GnContent (gnsdk_gdo_handle_t gdoHandle)
GnAsset Asset (GnImageSize imageSize) const
asset_iterable Assets () const
GnContentType ContentType () const
gnsdk_cstr_t Id () const
gnsdk_cstr_t MimeType () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
Provides access to content assets that can be retrieved from Urls. Content is only available is content is enabled from the original query's lookup data. Use the query object's options to enable content. The type of content that is available depends on the parent object. For example you can access album cover art from a GnAlbum object, but not an artist image. To retrieve an artist image navigate to a GnContributor object and invoke it's GnContent instance.
Constructor & Destructor Documentation
GNWRAPPER_ANNOTATE gracenote::metadata::GnContent::GnContent () inline
Constructs empty GnContent object
gracenote::metadata::GnContent::GnContent (gnsdk_gdo_handle_t gdoHandle) inline
Constructs a GnContent object from a native handle
Parameters
gdoHandle [in] Native handle
Member Function Documentation
GnAsset gracenote::metadata::GnContent::Asset (GnImageSize imageSize) const inline
Asset by image size (if applicable)
Parameters
imageSize [in] Image size
Returns
Asset object
References gracenote::kImageSize110, gracenote::kImageSize220, gracenote::kImageSize300, gracenote::kImageSizeLarge, gracenote::kImageSizeMedium, gracenote::kImageSizeSmall, gracenote::kImageSizeThumbnail, gracenote::kImageSizeUnknown, and gracenote::kImageSizeXLarge.
asset_iterable gracenote::metadata::GnContent::Assets () const inline
Iterator for the external third-party IDs (e.g., Amazon's) associated with this contributor.
Returns
Iterator
GnContentType gracenote::metadata::GnContent::ContentType () const inline
Content type - cover art, biography, etc.
Returns
Content type
References gracenote::gnstd::gn_strcmp(), gracenote::GnObject::IsNull(), gracenote::kContentTypeArtistNews, gracenote::kContentTypeBiography, gracenote::kContentTypeImageArtist, gracenote::kContentTypeImageCover, gracenote::kContentTypeImageVideo, gracenote::kContentTypeListenerComments, gracenote::kContentTypeNews, gracenote::kContentTypeNull, gracenote::kContentTypeReleaseComments, gracenote::kContentTypeReview, gracenote::kContentTypeUnknown, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContent::Id () const inline
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContent::MimeType () const inline
Content's mime type
Returns
Mime type
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.