GNSDK for Desktop: gracenote::metadata::GnContributor Class Reference
gracenote::metadata::GnContributor Class Reference
Public Member Functions
GnContributor ()
GnContributor (gnsdk_gdo_handle_t gdoHandle)
GnContributor (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError)
virtual ~GnContributor ()
gnsdk_cstr_t ArtistType (GnDataLevel level) const
GnContent Biography () const
gnsdk_cstr_t BiographyVideo () const
gnsdk_cstr_t BirthDate () const
gnsdk_cstr_t BirthPlace () const
GnContributor Collaborator () const
bool CollaboratorResult () const
GnContent Content (GnContentType contentType) const
content_iterable Contents () const
gnsdk_cstr_t DeathDate () const
gnsdk_cstr_t DeathPlace () const
gnsdk_cstr_t Era (GnDataLevel level) const
externalid_iterable ExternalIds () const
gnsdk_cstr_t Genre (GnDataLevel level) const
gnsdk_cstr_t GnId () const
GNWRAPPER_ANNOTATE GNSDK_CHECKED_CAST (GnContributor, GNSDK_GDO_TYPE_CONTRIBUTOR)
gnsdk_cstr_t GnUId () const
GnContent Image () const
bool IsFullResult () const
gnsdk_cstr_t MediaSpace () const
GnName Name () const
name_iterable NamesOfficial () const
name_iterable NamesRegional () const
gnsdk_cstr_t Origin (GnDataLevel level) const
gnsdk_cstr_t ProductId () const
gnsdk_cstr_t Tui () const
gnsdk_cstr_t TuiTag () const
Public Member Functions inherited from gracenote::metadata::GnDataObject
GNWRAPPER_ANNOTATE GnDataObject ()
GnDataObject (const GnDataObject &obj)
GnDataObject (gnsdk_gdo_handle_t gdoHandle)
GnDataObject (gnsdk_cstr_t id, gnsdk_cstr_t idTag, gnsdk_cstr_t idSrc) throw (GnError)
GnDataObject Child (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_uint32_t ChildCount (gnsdk_cstr_t childKey) const
template<typename gdoType >
gdoType ChildGet (gnsdk_cstr_t childKey, gnsdk_uint32_t childOrdinal=1) const
gnsdk_cstr_t GetType () const throw (GnError)
bool IsType (gnsdk_cstr_t strType) const throw (GnError)
void Locale (const GnLocale &locale) const throw (GnError)
gnsdk_gdo_handle_t native () const
template<typename gdoType >
gdoType Reflect () const
GnString Render (const GnRenderOptions &options) const throw (GnError)
GnString Serialize () const throw (GnError)
gnsdk_cstr_t StringValue (gnsdk_cstr_t valueKey, gnsdk_uint32_t ordinal=1) const
gnsdk_uint32_t StringValueCount (gnsdk_cstr_t valueKey) const
Public Member Functions inherited from gracenote::GnObject
bool IsNull () const
virtual bool operator!= (const GnObject &rhs) const
virtual bool operator== (const GnObject &rhs) const
Additional Inherited Members
Static Public Member Functions inherited from gracenote::metadata::GnDataObject
static GnDataObject CreateFromXml (gnsdk_cstr_t xml) throw (GnError)
static GnDataObject Deserialize (gnsdk_cstr_t serializedGdo) throw (GnError)
Detailed Description
A person participating Album or Track creation. Provides access to artist image when received from a query object with content enabled in lookup data.
Constructor & Destructor Documentation
gracenote::metadata::GnContributor::GnContributor () inline
Constructs empty GnContributor object
gracenote::metadata::GnContributor::GnContributor (gnsdk_gdo_handle_t gdoHandle) inline
Constructs a GnContributor from a native handle
Parameters
gdohandle [in] Native handle
gracenote::metadata::GnContributor::GnContributor (gnsdk_cstr_t id, gnsdk_cstr_t idTag) throw (GnError) inline
Constructs a GnContributor from a Gracenote identifier and identifier tag
Parameters
id [in] Identifier
idTag [in] Identifier tag
virtual gracenote::metadata::GnContributor::~GnContributor () inline virtual
Member Function Documentation
gnsdk_cstr_t gracenote::metadata::GnContributor::ArtistType (GnDataLevel level) const inline
Contributor's artist type. List/locale dependent, multi-level field.
Parameters
level [in] Data level
Returns
Artist type
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, and gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnContributor::Biography () const inline
Fetch the contributor's biography content object.
Returns
Content object
gnsdk_cstr_t gracenote::metadata::GnContributor::BiographyVideo () const inline
Contributor's biography when received from a video response. When the contributor object was derived from a video response use this method to btain the biography.
Returns
Biography
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::BirthDate () const inline
Contributor's birth date.
Returns
Date of birth
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::BirthPlace () const inline
Contributor's place of birth.
Returns
Place of birth
References gracenote::metadata::GnDataObject::StringValue().
GnContributor gracenote::metadata::GnContributor::Collaborator () const inline
Contributor that collaborated with this contributor in the context of the returned result.
Returns
Contributor
bool gracenote::metadata::GnContributor::CollaboratorResult () const inline
Get flag indicating if this is a collaborator result
Returns
True if a collaborator result, false otherwise
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnContributor::Content (GnContentType contentType) const inline
Content (cover art, review, etc) object
Parameters
GnContentType object
Returns
Content object
References gracenote::gnconvert::_convertContentTypeCppC().
content_iterable gracenote::metadata::GnContributor::Contents () const inline
Iterator for contirbutor associated content.
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnContributor::DeathDate () const inline
Date contributor died
Returns
Date of death
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::DeathPlace () const inline
Contributor's place of death.
Returns
Place of death
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::Era (GnDataLevel level) const inline
Contributor's era. List/locale dependent, multi-level field.
Parameters
level [in] Data level
Returns
Era
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
externalid_iterable gracenote::metadata::GnContributor::ExternalIds () const inline
Iterator for contributor associated external IDs (3rd party IDs, e.g., Amazon's)
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnContributor::Genre (GnDataLevel level) const inline
Contributor's genre. List/locale, multi-level field.
Parameters
level [in] Data level
Returns
Genre
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::GnId () const inline
Contributor's Gracenote identifier
Returns
Gracenote ID
References gracenote::metadata::GnDataObject::StringValue().
GNWRAPPER_ANNOTATE gracenote::metadata::GnContributor::GNSDK_CHECKED_CAST (GnContributor , GNSDK_GDO_TYPE_CONTRIBUTOR)
gnsdk_cstr_t gracenote::metadata::GnContributor::GnUId () const inline
Contributor's Gracenote unique identifier.
Returns
Gracenote Unique ID
References gracenote::metadata::GnDataObject::StringValue().
GnContent gracenote::metadata::GnContributor::Image () const inline
Fetch the contributor's image content object
Returns
Content object
bool gracenote::metadata::GnContributor::IsFullResult () const inline
Flag indicating if data object response contains full (true) or partial metadata. Returns true if full, false if partial.
Note:
What constitutes a full result varies among the individual response types and results, and also depends on data availability.
References gracenote::gnstd::gn_strtobool(), and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::MediaSpace () const inline
Contributor's media space, e.g., music, film, stage. List/locale dependent field.
Returns
Media space
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::GnDataObject::StringValue().
GnName gracenote::metadata::GnContributor::Name () const inline
Contributor name object
Returns
Name
name_iterable gracenote::metadata::GnContributor::NamesOfficial () const inline
Iterator for accessing the contributor's official name(s).
Returns
Iterator
name_iterable gracenote::metadata::GnContributor::NamesRegional () const inline
Iterator for accessing the contributor's regional name(s).
Returns
Iterator
gnsdk_cstr_t gracenote::metadata::GnContributor::Origin (GnDataLevel level) const inline
Contributor's origin, e.g., New York City
Parameters
level [in] Data level
Returns
Origin
Remarks:
This is a list-based value requiring that a corresponding locale or list be loaded.
References gracenote::metadata::kDataLevel_1, gracenote::metadata::kDataLevel_2, gracenote::metadata::kDataLevel_3, gracenote::metadata::kDataLevel_4, and gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::ProductId () const inline
Retrieves the contributor's product identifier.
Returns
Gracenote Product ID
Remarks:
Available for most types, this retrieves a value which can be stored or transmitted. This value can be used as a static identifier for the current content as it will not change over time.
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::Tui () const inline
Contributor's Gracenote Tui (title-unique identifier)
Returns
Tui
References gracenote::metadata::GnDataObject::StringValue().
gnsdk_cstr_t gracenote::metadata::GnContributor::TuiTag () const inline
Contributor's Gracenote Tui Tag
Returns
Tui Tag
References gracenote::metadata::GnDataObject::StringValue().
How can we improve this documentation?
Copyright © 2000-present. Gracenote, Inc. All rights reserved. Generated on Tue Jul 14 2015 12:48:50.