/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnStringValueIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnStringValueIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnStringValueIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnStringValueIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String __ref__() {
    return gnsdk_javaJNI.GnStringValueIterator___ref__(swigCPtr, this);
  }

  public String next() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnStringValueIterator_next(swigCPtr, this);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnStringValueIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnStringValueIterator itr) {
    return gnsdk_javaJNI.GnStringValueIterator_distance(swigCPtr, this, GnStringValueIterator.getCPtr(itr), itr);
  }

  public GnStringValueIterator(gn_gdo_string_provider provider, long pos) {
    this(gnsdk_javaJNI.new_GnStringValueIterator__SWIG_0(gn_gdo_string_provider.getCPtr(provider), provider, pos), true);
  }

  public GnStringValueIterator(GnStringValueIterator copy) {
    this(gnsdk_javaJNI.new_GnStringValueIterator__SWIG_1(GnStringValueIterator.getCPtr(copy), copy), true);
  }

}
