/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoWorkIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoWorkIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoWorkIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoWorkIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoWork __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnVideoWork(gnsdk_javaJNI.GnVideoWorkIterator___ref__(swigCPtr, this), false);
  }

  public GnVideoWork next() throws com.gracenote.gnsdk.GnException {
    return new GnVideoWork(gnsdk_javaJNI.GnVideoWorkIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnVideoWorkIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnVideoWorkIterator itr) {
    return gnsdk_javaJNI.GnVideoWorkIterator_distance(swigCPtr, this, GnVideoWorkIterator.getCPtr(itr), itr);
  }

  public GnVideoWorkIterator(GnVideoWorkProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnVideoWorkIterator(GnVideoWorkProvider.getCPtr(provider), provider, pos), true);
  }

}
