/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoProductIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoProductIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoProductIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoProductIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoProduct __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnVideoProduct(gnsdk_javaJNI.GnVideoProductIterator___ref__(swigCPtr, this), false);
  }

  public GnVideoProduct next() throws com.gracenote.gnsdk.GnException {
    return new GnVideoProduct(gnsdk_javaJNI.GnVideoProductIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnVideoProductIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnVideoProductIterator itr) {
    return gnsdk_javaJNI.GnVideoProductIterator_distance(swigCPtr, this, GnVideoProductIterator.getCPtr(itr), itr);
  }

  public GnVideoProductIterator(GnVideoProductProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnVideoProductIterator(GnVideoProductProvider.getCPtr(provider), provider, pos), true);
  }

}
