/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoSeriesIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoSeriesIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoSeriesIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoSeriesIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoSeries __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnVideoSeries(gnsdk_javaJNI.GnVideoSeriesIterator___ref__(swigCPtr, this), false);
  }

  public GnVideoSeries next() throws com.gracenote.gnsdk.GnException {
    return new GnVideoSeries(gnsdk_javaJNI.GnVideoSeriesIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnVideoSeriesIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnVideoSeriesIterator itr) {
    return gnsdk_javaJNI.GnVideoSeriesIterator_distance(swigCPtr, this, GnVideoSeriesIterator.getCPtr(itr), itr);
  }

  public GnVideoSeriesIterator(GnVideoSeriesProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnVideoSeriesIterator(GnVideoSeriesProvider.getCPtr(provider), provider, pos), true);
  }

}
