/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

class IGnCancellableProxy implements  IGnCancellable  {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IGnCancellableProxy(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGnCancellableProxy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_IGnCancellableProxy(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCancel(boolean bCancel) {
    gnsdk_javaJNI.IGnCancellableProxy_setCancel(swigCPtr, this, bCancel);
  }

  public boolean isCancelled() {
    return gnsdk_javaJNI.IGnCancellableProxy_isCancelled(swigCPtr, this);
  }

}
