/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

class IGnSystemEventsProxyL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IGnSystemEventsProxyL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGnSystemEventsProxyL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_IGnSystemEventsProxyL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  protected void swigReleaseOwnership() {
    swigCMemOwn = false;
    gnsdk_javaJNI.IGnSystemEventsProxyL_change_ownership(this, swigCPtr, false);
  }

  protected void swigTakeOwnership() {
    swigCMemOwn = true;
    gnsdk_javaJNI.IGnSystemEventsProxyL_change_ownership(this, swigCPtr, true);
  }

  public void localeUpdateNeeded(GnLocale locale) {
    gnsdk_javaJNI.IGnSystemEventsProxyL_localeUpdateNeeded(swigCPtr, this, GnLocale.getCPtr(locale), locale);
  }

  public void listUpdateNeeded(GnList list) {
    gnsdk_javaJNI.IGnSystemEventsProxyL_listUpdateNeeded(swigCPtr, this, GnList.getCPtr(list), list);
  }

  public void systemMemoryWarning(long curMemSize, long memoryWarnSize) {
    gnsdk_javaJNI.IGnSystemEventsProxyL_systemMemoryWarning(swigCPtr, this, curMemSize, memoryWarnSize);
  }

  public IGnSystemEventsProxyL() {
    this(gnsdk_javaJNI.new_IGnSystemEventsProxyL(), true);
    gnsdk_javaJNI.IGnSystemEventsProxyL_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
