/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnContributorEnumerable : System.Collections.Generic.IEnumerable<GnContributor>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnContributorEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnContributorEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnContributorEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnContributorEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnContributor> System.Collections.Generic.IEnumerable<GnContributor> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnContributorEnumerable(GnContributorProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnContributorEnumerable(GnContributorProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnContributorEnumerator GetEnumerator() {
    GnContributorEnumerator ret = new GnContributorEnumerator(gnsdk_csharp_marshalPINVOKE.GnContributorEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnContributorEnumerator end() {
    GnContributorEnumerator ret = new GnContributorEnumerator(gnsdk_csharp_marshalPINVOKE.GnContributorEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnContributorEnumerable_count(swigCPtr);
    return ret;
  }

  public GnContributorEnumerator at(uint index) {
    GnContributorEnumerator ret = new GnContributorEnumerator(gnsdk_csharp_marshalPINVOKE.GnContributorEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnContributorEnumerator getByIndex(uint index) {
    GnContributorEnumerator ret = new GnContributorEnumerator(gnsdk_csharp_marshalPINVOKE.GnContributorEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
