/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnLocaleInfoEnumerable : System.Collections.Generic.IEnumerable<GnLocaleInfo>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnLocaleInfoEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnLocaleInfoEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnLocaleInfoEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnLocaleInfoEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<GnLocaleInfo> System.Collections.Generic.IEnumerable<GnLocaleInfo>.GetEnumerator( )
{
return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
return GetEnumerator( );
}

  public GnLocaleInfoEnumerable(locale_info_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnLocaleInfoEnumerable(locale_info_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnLocaleInfoEnumerator GetEnumerator() {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnLocaleInfoEnumerator end() {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_count(swigCPtr);
    return ret;
  }

  public GnLocaleInfoEnumerator at(uint index) {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnLocaleInfoEnumerator getByIndex(uint index) {
    GnLocaleInfoEnumerator ret = new GnLocaleInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnLocaleInfoEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
