/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnMoodgridProviderEnumerable : System.Collections.Generic.IEnumerable<GnMoodgridProvider >, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMoodgridProviderEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnMoodgridProviderEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMoodgridProviderEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMoodgridProviderEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<GnMoodgridProvider> System.Collections.Generic.IEnumerable<GnMoodgridProvider>.GetEnumerator( )
{
	return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
	return GetEnumerator( );
}

  public GnMoodgridProviderEnumerable(moodgrid_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnMoodgridProviderEnumerable(moodgrid_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMoodgridProviderEnumerator GetEnumerator() {
    GnMoodgridProviderEnumerator ret = new GnMoodgridProviderEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridProviderEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnMoodgridProviderEnumerator end() {
    GnMoodgridProviderEnumerator ret = new GnMoodgridProviderEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridProviderEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnMoodgridProviderEnumerable_count(swigCPtr);
    return ret;
  }

  public GnMoodgridProviderEnumerator at(uint index) {
    GnMoodgridProviderEnumerator ret = new GnMoodgridProviderEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridProviderEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnMoodgridProviderEnumerator getByIndex(uint index) {
    GnMoodgridProviderEnumerator ret = new GnMoodgridProviderEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridProviderEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
