/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnMoodgridResultEnumerable : System.Collections.Generic.IEnumerable<GnMoodgridIdentifier> {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMoodgridResultEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnMoodgridResultEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMoodgridResultEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMoodgridResultEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

	System.Collections.Generic.IEnumerator<GnMoodgridIdentifier> System.Collections.Generic.IEnumerable<GnMoodgridIdentifier> .GetEnumerator( )
	{
		return GetEnumerator();
	}
	System.Collections.IEnumerator System.Collections.IEnumerable.
		GetEnumerator( )
	{
		return GetEnumerator();
	}


  public GnMoodgridResultEnumerable(moodgrid_result_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnMoodgridResultEnumerable(moodgrid_result_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMoodgridResultEnumerator GetEnumerator() {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnMoodgridResultEnumerator end() {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_count(swigCPtr);
    return ret;
  }

  public GnMoodgridResultEnumerator at(uint index) {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnMoodgridResultEnumerator getByIndex(uint index) {
    GnMoodgridResultEnumerator ret = new GnMoodgridResultEnumerator(gnsdk_csharp_marshalPINVOKE.GnMoodgridResultEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
