/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnMusicIdFileInfoEnumerable : System.Collections.Generic.IEnumerable<GnMusicIdFileInfo>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMusicIdFileInfoEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnMusicIdFileInfoEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMusicIdFileInfoEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMusicIdFileInfoEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

	System.Collections.Generic.IEnumerator<GnMusicIdFileInfo> System.Collections.Generic.IEnumerable<GnMusicIdFileInfo> .GetEnumerator( )
	{
		return GetEnumerator();
	}
	System.Collections.IEnumerator System.Collections.IEnumerable.
		GetEnumerator( )
	{
		return GetEnumerator();
	}


  public GnMusicIdFileInfoEnumerable(musicid_file_info_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnMusicIdFileInfoEnumerable(musicid_file_info_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMusicIdFileInfoEnumerator GetEnumerator() {
    GnMusicIdFileInfoEnumerator ret = new GnMusicIdFileInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnMusicIdFileInfoEnumerator end() {
    GnMusicIdFileInfoEnumerator ret = new GnMusicIdFileInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEnumerable_count(swigCPtr);
    return ret;
  }

  public GnMusicIdFileInfoEnumerator at(uint index) {
    GnMusicIdFileInfoEnumerator ret = new GnMusicIdFileInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnMusicIdFileInfoEnumerator getByIndex(uint index) {
    GnMusicIdFileInfoEnumerator ret = new GnMusicIdFileInfoEnumerator(gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
