/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnMusicIdFileInfoEventsDelegate : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnMusicIdFileInfoEventsDelegate(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnMusicIdFileInfoEventsDelegate obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnMusicIdFileInfoEventsDelegate() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnMusicIdFileInfoEventsDelegate(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public virtual void GatherFingerprint(GnMusicIdFileInfo fileinfo, uint currentFile, uint totalFiles, IGnCancellable canceller) {
    gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEventsDelegate_GatherFingerprint(swigCPtr, GnMusicIdFileInfo.getCPtr(fileinfo), currentFile, totalFiles, IGnCancellable.getCPtr(canceller));
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void GatherMetadata(GnMusicIdFileInfo fileinfo, uint currentFile, uint totalFiles, IGnCancellable canceller) {
    gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEventsDelegate_GatherMetadata(swigCPtr, GnMusicIdFileInfo.getCPtr(fileinfo), currentFile, totalFiles, IGnCancellable.getCPtr(canceller));
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnMusicIdFileInfoEventsDelegate() : this(gnsdk_csharp_marshalPINVOKE.new_GnMusicIdFileInfoEventsDelegate(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("GatherFingerprint", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateGnMusicIdFileInfoEventsDelegate_0(SwigDirectorGatherFingerprint);
    if (SwigDerivedClassHasMethod("GatherMetadata", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateGnMusicIdFileInfoEventsDelegate_1(SwigDirectorGatherMetadata);
    gnsdk_csharp_marshalPINVOKE.GnMusicIdFileInfoEventsDelegate_director_connect(swigCPtr, swigDelegate0, swigDelegate1);
  }

  private bool SwigDerivedClassHasMethod(string methodName, Type[] methodTypes) {
    System.Reflection.MethodInfo methodInfo = this.GetType().GetMethod(methodName, System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance, null, methodTypes, null);
    bool hasDerivedMethod = methodInfo.DeclaringType.IsSubclassOf(typeof(GnMusicIdFileInfoEventsDelegate));
    return hasDerivedMethod;
  }

  private void SwigDirectorGatherFingerprint(IntPtr fileinfo, uint currentFile, uint totalFiles, IntPtr canceller) {
    GatherFingerprint(new GnMusicIdFileInfo(fileinfo, false), currentFile, totalFiles, new IGnCancellable(canceller, false));
  }

  private void SwigDirectorGatherMetadata(IntPtr fileinfo, uint currentFile, uint totalFiles, IntPtr canceller) {
    GatherMetadata(new GnMusicIdFileInfo(fileinfo, false), currentFile, totalFiles, new IGnCancellable(canceller, false));
  }

  public delegate void SwigDelegateGnMusicIdFileInfoEventsDelegate_0(IntPtr fileinfo, uint currentFile, uint totalFiles, IntPtr canceller);
  public delegate void SwigDelegateGnMusicIdFileInfoEventsDelegate_1(IntPtr fileinfo, uint currentFile, uint totalFiles, IntPtr canceller);

  private SwigDelegateGnMusicIdFileInfoEventsDelegate_0 swigDelegate0;
  private SwigDelegateGnMusicIdFileInfoEventsDelegate_1 swigDelegate1;

  private static Type[] swigMethodTypes0 = new Type[] { typeof(GnMusicIdFileInfo), typeof(uint), typeof(uint), typeof(IGnCancellable) };
  private static Type[] swigMethodTypes1 = new Type[] { typeof(GnMusicIdFileInfo), typeof(uint), typeof(uint), typeof(IGnCancellable) };
}

}
