/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnPlaylistAttributeEnumerable : System.Collections.Generic.IEnumerable<String >, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnPlaylistAttributeEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnPlaylistAttributeEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnPlaylistAttributeEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnPlaylistAttributeEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

System.Collections.Generic.IEnumerator<string> System.Collections.Generic.IEnumerable<string>.GetEnumerator( )
{
	return GetEnumerator( );
}
System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator( )
{
	return GetEnumerator( );
}

  public GnPlaylistAttributeEnumerable(attribute_provider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnPlaylistAttributeEnumerable(attribute_provider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnPlaylistAttributeEnumerator GetEnumerator() {
    GnPlaylistAttributeEnumerator ret = new GnPlaylistAttributeEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnPlaylistAttributeEnumerator end() {
    GnPlaylistAttributeEnumerator ret = new GnPlaylistAttributeEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerable_count(swigCPtr);
    return ret;
  }

  public GnPlaylistAttributeEnumerator at(uint index) {
    GnPlaylistAttributeEnumerator ret = new GnPlaylistAttributeEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnPlaylistAttributeEnumerator getByIndex(uint index) {
    GnPlaylistAttributeEnumerator ret = new GnPlaylistAttributeEnumerator(gnsdk_csharp_marshalPINVOKE.GnPlaylistAttributeEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
