/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnStringValueEnumerator : System.Collections.Generic.IEnumerator<System.String>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnStringValueEnumerator(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnStringValueEnumerator obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnStringValueEnumerator() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnStringValueEnumerator(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			public bool
			MoveNext( )
			{
				return hasNext( );
			}

			public System.String Current {
				get {
					return next( );
				}
			}
			object System.Collections.IEnumerator.Current {
				get {
					return Current;
				}
			}
			public void
			Reset( )
			{
			}
		
  public string __ref__() {
    string ret = gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerator___ref__(swigCPtr);
    return ret;
  }

  public string next() {
	IntPtr temp = gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerator_next(swigCPtr); 
	return GnMarshalUTF8.StringFromNativeUtf8(temp);
}

  public bool hasNext() {
    bool ret = gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerator_hasNext(swigCPtr);
    return ret;
  }

  public uint distance(GnStringValueEnumerator itr) {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnStringValueEnumerator_distance(swigCPtr, GnStringValueEnumerator.getCPtr(itr));
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public GnStringValueEnumerator(gn_gdo_string_provider provider, uint pos) : this(gnsdk_csharp_marshalPINVOKE.new_GnStringValueEnumerator__SWIG_0(gn_gdo_string_provider.getCPtr(provider), pos), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnStringValueEnumerator(GnStringValueEnumerator copy) : this(gnsdk_csharp_marshalPINVOKE.new_GnStringValueEnumerator__SWIG_1(GnStringValueEnumerator.getCPtr(copy)), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
