/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnVideoFeatureEnumerable : System.Collections.Generic.IEnumerable<GnVideoFeature>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnVideoFeatureEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnVideoFeatureEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnVideoFeatureEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnVideoFeatureEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnVideoFeature> System.Collections.Generic.IEnumerable<GnVideoFeature> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnVideoFeatureEnumerable(GnVideoFeatureProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnVideoFeatureEnumerable(GnVideoFeatureProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnVideoFeatureEnumerator GetEnumerator() {
    GnVideoFeatureEnumerator ret = new GnVideoFeatureEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoFeatureEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnVideoFeatureEnumerator end() {
    GnVideoFeatureEnumerator ret = new GnVideoFeatureEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoFeatureEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnVideoFeatureEnumerable_count(swigCPtr);
    return ret;
  }

  public GnVideoFeatureEnumerator at(uint index) {
    GnVideoFeatureEnumerator ret = new GnVideoFeatureEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoFeatureEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnVideoFeatureEnumerator getByIndex(uint index) {
    GnVideoFeatureEnumerator ret = new GnVideoFeatureEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoFeatureEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
