/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnVideoSideEnumerable : System.Collections.Generic.IEnumerable<GnVideoSide>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnVideoSideEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnVideoSideEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnVideoSideEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnVideoSideEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnVideoSide> System.Collections.Generic.IEnumerable<GnVideoSide> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnVideoSideEnumerable(GnVideoSideProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnVideoSideEnumerable(GnVideoSideProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnVideoSideEnumerator GetEnumerator() {
    GnVideoSideEnumerator ret = new GnVideoSideEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoSideEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnVideoSideEnumerator end() {
    GnVideoSideEnumerator ret = new GnVideoSideEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoSideEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnVideoSideEnumerable_count(swigCPtr);
    return ret;
  }

  public GnVideoSideEnumerator at(uint index) {
    GnVideoSideEnumerator ret = new GnVideoSideEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoSideEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnVideoSideEnumerator getByIndex(uint index) {
    GnVideoSideEnumerator ret = new GnVideoSideEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoSideEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
