/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnVideoWorkEnumerable : System.Collections.Generic.IEnumerable<GnVideoWork>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnVideoWorkEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnVideoWorkEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnVideoWorkEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnVideoWorkEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnVideoWork> System.Collections.Generic.IEnumerable<GnVideoWork> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnVideoWorkEnumerable(GnVideoWorkProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnVideoWorkEnumerable(GnVideoWorkProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnVideoWorkEnumerator GetEnumerator() {
    GnVideoWorkEnumerator ret = new GnVideoWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoWorkEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnVideoWorkEnumerator end() {
    GnVideoWorkEnumerator ret = new GnVideoWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoWorkEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnVideoWorkEnumerable_count(swigCPtr);
    return ret;
  }

  public GnVideoWorkEnumerator at(uint index) {
    GnVideoWorkEnumerator ret = new GnVideoWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoWorkEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnVideoWorkEnumerator getByIndex(uint index) {
    GnVideoWorkEnumerator ret = new GnVideoWorkEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoWorkEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
