/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnVideoLayerEnumerable : System.Collections.Generic.IEnumerable<GnVideoLayer>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnVideoLayerEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnVideoLayerEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnVideoLayerEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnVideoLayerEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnVideoLayer> System.Collections.Generic.IEnumerable<GnVideoLayer> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnVideoLayerEnumerable(GnVideoLayerProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnVideoLayerEnumerable(GnVideoLayerProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnVideoLayerEnumerator GetEnumerator() {
    GnVideoLayerEnumerator ret = new GnVideoLayerEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoLayerEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnVideoLayerEnumerator end() {
    GnVideoLayerEnumerator ret = new GnVideoLayerEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoLayerEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnVideoLayerEnumerable_count(swigCPtr);
    return ret;
  }

  public GnVideoLayerEnumerator at(uint index) {
    GnVideoLayerEnumerator ret = new GnVideoLayerEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoLayerEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnVideoLayerEnumerator getByIndex(uint index) {
    GnVideoLayerEnumerator ret = new GnVideoLayerEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoLayerEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
