/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace GracenoteSDK {

using System;
using System.Runtime.InteropServices;

public class GnVideoCreditEnumerable : System.Collections.Generic.IEnumerable<GnVideoCredit>, IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GnVideoCreditEnumerable(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(GnVideoCreditEnumerable obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~GnVideoCreditEnumerable() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          gnsdk_csharp_marshalPINVOKE.delete_GnVideoCreditEnumerable(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

			System.Collections.Generic.IEnumerator<GnVideoCredit> System.Collections.Generic.IEnumerable<GnVideoCredit> .GetEnumerator( )
			{
				return GetEnumerator( );
			}
			System.Collections.IEnumerator System.Collections.IEnumerable.
			    GetEnumerator( )
			{
				return GetEnumerator( );
			}

		
  public GnVideoCreditEnumerable(GnVideoCreditProvider provider, uint start) : this(gnsdk_csharp_marshalPINVOKE.new_GnVideoCreditEnumerable(GnVideoCreditProvider.getCPtr(provider), start), true) {
    if (gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Pending) throw gnsdk_csharp_marshalPINVOKE.SWIGPendingException.Retrieve();
  }

  public GnVideoCreditEnumerator GetEnumerator() {
    GnVideoCreditEnumerator ret = new GnVideoCreditEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoCreditEnumerable_GetEnumerator(swigCPtr), true);
    return ret;
  }

  public GnVideoCreditEnumerator end() {
    GnVideoCreditEnumerator ret = new GnVideoCreditEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoCreditEnumerable_end(swigCPtr), true);
    return ret;
  }

  public uint count() {
    uint ret = gnsdk_csharp_marshalPINVOKE.GnVideoCreditEnumerable_count(swigCPtr);
    return ret;
  }

  public GnVideoCreditEnumerator at(uint index) {
    GnVideoCreditEnumerator ret = new GnVideoCreditEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoCreditEnumerable_at(swigCPtr, index), true);
    return ret;
  }

  public GnVideoCreditEnumerator getByIndex(uint index) {
    GnVideoCreditEnumerator ret = new GnVideoCreditEnumerator(gnsdk_csharp_marshalPINVOKE.GnVideoCreditEnumerable_getByIndex(swigCPtr, index), true);
    return ret;
  }

}

}
