/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnAudioWork extends GnDataObject {
  private long swigCPtr;

  protected GnAudioWork(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnAudioWork_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnAudioWork obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnAudioWork(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnAudioWork_gnType();
  }

  public static GnAudioWork from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnAudioWork(gnsdk_javaJNI.GnAudioWork_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public GnTitle title() {
    return new GnTitle(gnsdk_javaJNI.GnAudioWork_title(swigCPtr, this), true);
  }

  public GnCredit credit() {
    return new GnCredit(gnsdk_javaJNI.GnAudioWork_credit(swigCPtr, this), true);
  }

  public String tui() {
    return gnsdk_javaJNI.GnAudioWork_tui(swigCPtr, this);
  }

  public String tuiTag() {
    return gnsdk_javaJNI.GnAudioWork_tuiTag(swigCPtr, this);
  }

  public String tagId() {
    return gnsdk_javaJNI.GnAudioWork_tagId(swigCPtr, this);
  }

  public String gnId() {
    return gnsdk_javaJNI.GnAudioWork_gnId(swigCPtr, this);
  }

  public String gnUId() {
    return gnsdk_javaJNI.GnAudioWork_gnUId(swigCPtr, this);
  }

  public String productId() {
    return gnsdk_javaJNI.GnAudioWork_productId(swigCPtr, this);
  }

  public String origin(GnDataLevel level) {
    return gnsdk_javaJNI.GnAudioWork_origin(swigCPtr, this, level.swigValue());
  }

  public String era(GnDataLevel level) {
    return gnsdk_javaJNI.GnAudioWork_era(swigCPtr, this, level.swigValue());
  }

  public String genre(GnDataLevel level) {
    return gnsdk_javaJNI.GnAudioWork_genre(swigCPtr, this, level.swigValue());
  }

  public String compositionForm() {
    return gnsdk_javaJNI.GnAudioWork_compositionForm(swigCPtr, this);
  }

}
