/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnContributorIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnContributorIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnContributorIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnContributorIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnContributor __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnContributor(gnsdk_javaJNI.GnContributorIterator___ref__(swigCPtr, this), false);
  }

  public GnContributor next() throws com.gracenote.gnsdk.GnException {
    return new GnContributor(gnsdk_javaJNI.GnContributorIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnContributorIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnContributorIterator itr) {
    return gnsdk_javaJNI.GnContributorIterator_distance(swigCPtr, this, GnContributorIterator.getCPtr(itr), itr);
  }

  public GnContributorIterator(GnContributorProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnContributorIterator(GnContributorProvider.getCPtr(provider), provider, pos), true);
  }

}
