/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnDataObject extends GnObject {
  private long swigCPtr;

  protected GnDataObject(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnDataObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnDataObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnDataObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

	private GnLocale locale;
	
	private long getLocaleCppPtrAndSaveReference( GnLocale newLocale ) {
		locale = newLocale;
		return GnLocale.getCPtr(newLocale);
	}

  public GnDataObject(GnDataObject obj) {
    this(gnsdk_javaJNI.new_GnDataObject__SWIG_0(GnDataObject.getCPtr(obj), obj), true);
  }

  public GnDataObject(String id, String idTag, String idSrc) throws com.gracenote.gnsdk.GnException {
    this(gnsdk_javaJNI.new_GnDataObject__SWIG_1(id, idTag, idSrc), true);
  }

  public static GnDataObject deserialize(String serializedGdo) throws com.gracenote.gnsdk.GnException {
    return new GnDataObject(gnsdk_javaJNI.GnDataObject_deserialize(serializedGdo), true);
  }

  public static GnDataObject createFromXml(String xml) throws com.gracenote.gnsdk.GnException {
    return new GnDataObject(gnsdk_javaJNI.GnDataObject_createFromXml(xml), true);
  }

  public GnString serialize() throws com.gracenote.gnsdk.GnException {
    return new GnString(gnsdk_javaJNI.GnDataObject_serialize(swigCPtr, this), true);
  }

  public long stringValueCount(String valueKey) {
    return gnsdk_javaJNI.GnDataObject_stringValueCount(swigCPtr, this, valueKey);
  }

  public String stringValue(String valueKey, long ordinal) {
    return gnsdk_javaJNI.GnDataObject_stringValue__SWIG_0(swigCPtr, this, valueKey, ordinal);
  }

  public String stringValue(String valueKey) {
    return gnsdk_javaJNI.GnDataObject_stringValue__SWIG_1(swigCPtr, this, valueKey);
  }

  public long childCount(String childKey) {
    return gnsdk_javaJNI.GnDataObject_childCount(swigCPtr, this, childKey);
  }

  public GnDataObject child(String childKey, long childOrdinal) {
    return new GnDataObject(gnsdk_javaJNI.GnDataObject_child__SWIG_0(swigCPtr, this, childKey, childOrdinal), true);
  }

  public GnDataObject child(String childKey) {
    return new GnDataObject(gnsdk_javaJNI.GnDataObject_child__SWIG_1(swigCPtr, this, childKey), true);
  }

  public GnString render(GnRenderOptions options) throws com.gracenote.gnsdk.GnException {
    return new GnString(gnsdk_javaJNI.GnDataObject_render(swigCPtr, this, GnRenderOptions.getCPtr(options), options), true);
  }

  public void locale(GnLocale locale) throws com.gracenote.gnsdk.GnException {
    gnsdk_javaJNI.GnDataObject_locale(swigCPtr, this, getLocaleCppPtrAndSaveReference(locale), locale);
  }

  public String getType() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnDataObject_getType(swigCPtr, this);
  }

  public boolean isType(String strType) throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnDataObject_isType(swigCPtr, this, strType);
  }

}
