/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnList extends GnObject {
  private long swigCPtr;

  protected GnList(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnList_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnList(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

	private IGnStatusEvents pEventHandler;
	private IGnStatusEventsProxyU eventHandlerProxy;
	private GnLocale locale;

  public GnList(GnListType listType, GnLanguage language, GnRegion region, GnDescriptor descriptor, GnUser user, IGnStatusEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	this.locale = locale; 				// <REFERENCE_NAME_CHECK><TYPE>GnLocale</TYPE><NAME>locale</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnList__SWIG_0(listType.swigValue(), language.swigValue(), region.swigValue(), descriptor.swigValue(), GnUser.getCPtr(user), user, (eventHandlerProxy==null)?0:IGnStatusEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
}

  public GnList(GnListType listType, GnLanguage language, GnRegion region, GnDescriptor descriptor, GnUser user) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	this.locale = locale; 				// <REFERENCE_NAME_CHECK><TYPE>GnLocale</TYPE><NAME>locale</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnList__SWIG_1(listType.swigValue(), language.swigValue(), region.swigValue(), descriptor.swigValue(), GnUser.getCPtr(user), user);
}

  public GnList(GnListType listType, GnLocale locale, GnUser user, IGnStatusEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	this.locale = locale; 				// <REFERENCE_NAME_CHECK><TYPE>GnLocale</TYPE><NAME>locale</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnList__SWIG_2(listType.swigValue(), GnLocale.getCPtr(locale), locale, GnUser.getCPtr(user), user, (eventHandlerProxy==null)?0:IGnStatusEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
}

  public GnList(GnListType listType, GnLocale locale, GnUser user) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	this.locale = locale; 				// <REFERENCE_NAME_CHECK><TYPE>GnLocale</TYPE><NAME>locale</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnList__SWIG_3(listType.swigValue(), GnLocale.getCPtr(locale), locale, GnUser.getCPtr(user), user);
}

  public GnList(String serializedList) throws com.gracenote.gnsdk.GnException {
	this(0, true);
	
	eventHandlerProxy = new IGnStatusEventsProxyU(pEventHandler);
	this.pEventHandler=pEventHandler;	// <REFERENCE_NAME_CHECK><TYPE>IGnStatusEvents</TYPE><NAME>pEventHandler</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	this.locale = locale; 				// <REFERENCE_NAME_CHECK><TYPE>GnLocale</TYPE><NAME>locale</NAME></REFERENCE_NAME_CHECK> leave for scripted verification of names
	
	swigCPtr = gnsdk_javaJNI.new_GnList__SWIG_4(serializedList);
}

  public boolean update(GnUser user, IGnStatusEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_update__SWIG_0(swigCPtr, this, GnUser.getCPtr(user), user, (eventHandlerProxy==null)?0:IGnStatusEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
  }

  public boolean update(GnUser user) throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_update__SWIG_1(swigCPtr, this, GnUser.getCPtr(user), user);
  }

  public boolean updateCheck(GnUser user, IGnStatusEvents pEventHandler) throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_updateCheck__SWIG_0(swigCPtr, this, GnUser.getCPtr(user), user, (eventHandlerProxy==null)?0:IGnStatusEventsProxyL.getCPtr(eventHandlerProxy), eventHandlerProxy);
  }

  public boolean updateCheck(GnUser user) throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_updateCheck__SWIG_1(swigCPtr, this, GnUser.getCPtr(user), user);
  }

  public GnString serialize() throws com.gracenote.gnsdk.GnException {
    return new GnString(gnsdk_javaJNI.GnList_serialize(swigCPtr, this), true);
  }

  public GnString renderToXml(long levels, GnListRenderFlags renderFlags) throws com.gracenote.gnsdk.GnException {
    return new GnString(gnsdk_javaJNI.GnList_renderToXml(swigCPtr, this, levels, renderFlags.swigValue()), true);
  }

  public GnListType type() throws com.gracenote.gnsdk.GnException {
    return GnListType.swigToEnum(gnsdk_javaJNI.GnList_type(swigCPtr, this));
  }

  public GnDescriptor descriptor() throws com.gracenote.gnsdk.GnException {
    return GnDescriptor.swigToEnum(gnsdk_javaJNI.GnList_descriptor(swigCPtr, this));
  }

  public GnLanguage language() throws com.gracenote.gnsdk.GnException {
    return GnLanguage.swigToEnum(gnsdk_javaJNI.GnList_language(swigCPtr, this));
  }

  public GnRegion region() throws com.gracenote.gnsdk.GnException {
    return GnRegion.swigToEnum(gnsdk_javaJNI.GnList_region(swigCPtr, this));
  }

  public String revision() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_revision(swigCPtr, this);
  }

  public long levelCount() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnList_levelCount(swigCPtr, this);
  }

  public GnListElementIterable listElements(long level) {
    return new GnListElementIterable(gnsdk_javaJNI.GnList_listElements(swigCPtr, this, level), true);
  }

  public GnListElement elementById(long itemId) throws com.gracenote.gnsdk.GnException {
    return new GnListElement(gnsdk_javaJNI.GnList_elementById(swigCPtr, this, itemId), true);
  }

  public GnListElement elementByRange(long range) throws com.gracenote.gnsdk.GnException {
    return new GnListElement(gnsdk_javaJNI.GnList_elementByRange(swigCPtr, this, range), true);
  }

  public GnListElement elementByString(String strEquality) throws com.gracenote.gnsdk.GnException {
    return new GnListElement(gnsdk_javaJNI.GnList_elementByString(swigCPtr, this, strEquality), true);
  }

  public GnListElement elementByGnDataObject(GnDataObject dataObject, long ordinal, long level) throws com.gracenote.gnsdk.GnException {
    return new GnListElement(gnsdk_javaJNI.GnList_elementByGnDataObject(swigCPtr, this, GnDataObject.getCPtr(dataObject), dataObject, ordinal, level), true);
  }

}
