/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnListElement extends GnObject {
  private long swigCPtr;

  protected GnListElement(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnListElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnListElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnListElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String displayString() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_displayString(swigCPtr, this);
  }

  public long Id() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_Id(swigCPtr, this);
  }

  public long IdForSubmit() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_IdForSubmit(swigCPtr, this);
  }

  public String description() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_description(swigCPtr, this);
  }

  public String ratingTypeId() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_ratingTypeId(swigCPtr, this);
  }

  public GnListElement parent() throws com.gracenote.gnsdk.GnException {
    return new GnListElement(gnsdk_javaJNI.GnListElement_parent(swigCPtr, this), true);
  }

  public long level() throws com.gracenote.gnsdk.GnException {
    return gnsdk_javaJNI.GnListElement_level(swigCPtr, this);
  }

  public GnListElementChildIterable children() {
    return new GnListElementChildIterable(gnsdk_javaJNI.GnListElement_children(swigCPtr, this), true);
  }

}
