/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public enum GnLookupData {
  kLookupDataInvalid(0),
  kLookupDataContent,
  kLookupDataClassical,
  kLookupDataSonicData,
  kLookupDataPlaylist,
  kLookupDataExternalIds,
  kLookupDataGlobalIds,
  kLookupDataAdditionalCredits;

  protected final int swigValue() {
    return swigValue;
  }

  protected static GnLookupData swigToEnum(int swigValue) {
    GnLookupData[] swigValues = GnLookupData.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GnLookupData swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GnLookupData.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GnLookupData() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GnLookupData(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GnLookupData(GnLookupData swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

