/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnLogOptions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnLogOptions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnLogOptions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnLogOptions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnLogOptions() {
    this(gnsdk_javaJNI.new_GnLogOptions(), true);
  }

  public GnLogOptions synchronous(boolean bSyncWrite) {
    return new GnLogOptions(gnsdk_javaJNI.GnLogOptions_synchronous(swigCPtr, this, bSyncWrite), false);
  }

  public GnLogOptions archive(boolean bArchive) {
    return new GnLogOptions(gnsdk_javaJNI.GnLogOptions_archive(swigCPtr, this, bArchive), false);
  }

  public GnLogOptions archiveDaily() {
    return new GnLogOptions(gnsdk_javaJNI.GnLogOptions_archiveDaily(swigCPtr, this), false);
  }

  public GnLogOptions maxSize(java.math.BigInteger maxSize) {
    return new GnLogOptions(gnsdk_javaJNI.GnLogOptions_maxSize(swigCPtr, this, maxSize), false);
  }

}
