/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMoodgridPresentationDataIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMoodgridPresentationDataIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMoodgridPresentationDataIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMoodgridPresentationDataIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnMoodgridPresentationDataIterable(presentation_data_provider provider, long start) {
    this(gnsdk_javaJNI.new_GnMoodgridPresentationDataIterable(presentation_data_provider.getCPtr(provider), provider, start), true);
  }

  public GnMoodgridPresentationDataIterator getIterator() {
    return new GnMoodgridPresentationDataIterator(gnsdk_javaJNI.GnMoodgridPresentationDataIterable_getIterator(swigCPtr, this), true);
  }

  public GnMoodgridPresentationDataIterator end() {
    return new GnMoodgridPresentationDataIterator(gnsdk_javaJNI.GnMoodgridPresentationDataIterable_end(swigCPtr, this), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnMoodgridPresentationDataIterable_count(swigCPtr, this);
  }

  public GnMoodgridPresentationDataIterator at(long index) {
    return new GnMoodgridPresentationDataIterator(gnsdk_javaJNI.GnMoodgridPresentationDataIterable_at(swigCPtr, this, index), true);
  }

  public GnMoodgridPresentationDataIterator getByIndex(long index) {
    return new GnMoodgridPresentationDataIterator(gnsdk_javaJNI.GnMoodgridPresentationDataIterable_getByIndex(swigCPtr, this, index), true);
  }

}
