/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnMoodgridIdentifier {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnMoodgridIdentifier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnMoodgridIdentifier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnMoodgridIdentifier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String mediaIdentifier() {
    return gnsdk_javaJNI.GnMoodgridIdentifier_mediaIdentifier(swigCPtr, this);
  }

  public String group() {
    return gnsdk_javaJNI.GnMoodgridIdentifier_group(swigCPtr, this);
  }

}
