/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnName extends GnDataObject {
  private long swigCPtr;

  protected GnName(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnName_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnName obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnName(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnName_gnType();
  }

  public static GnName from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnName(gnsdk_javaJNI.GnName_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public String language() {
    return gnsdk_javaJNI.GnName_language(swigCPtr, this);
  }

  public String languageCode() {
    return gnsdk_javaJNI.GnName_languageCode(swigCPtr, this);
  }

  public String display() {
    return gnsdk_javaJNI.GnName_display(swigCPtr, this);
  }

  public String sortable() {
    return gnsdk_javaJNI.GnName_sortable(swigCPtr, this);
  }

  public String sortableScheme() {
    return gnsdk_javaJNI.GnName_sortableScheme(swigCPtr, this);
  }

  public String prefix() {
    return gnsdk_javaJNI.GnName_prefix(swigCPtr, this);
  }

  public String family() {
    return gnsdk_javaJNI.GnName_family(swigCPtr, this);
  }

  public String given() {
    return gnsdk_javaJNI.GnName_given(swigCPtr, this);
  }

  public String globalId() {
    return gnsdk_javaJNI.GnName_globalId(swigCPtr, this);
  }

}
