/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnRating extends GnDataObject {
  private long swigCPtr;

  protected GnRating(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnRating_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnRating obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnRating(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String rating() {
    return gnsdk_javaJNI.GnRating_rating(swigCPtr, this);
  }

  public String ratingType() {
    return gnsdk_javaJNI.GnRating_ratingType(swigCPtr, this);
  }

  public String ratingDesc() {
    return gnsdk_javaJNI.GnRating_ratingDesc(swigCPtr, this);
  }

  public long ratingTypeId() {
    return gnsdk_javaJNI.GnRating_ratingTypeId(swigCPtr, this);
  }

  public String ratingReason() {
    return gnsdk_javaJNI.GnRating_ratingReason(swigCPtr, this);
  }

  public String ratingMPAA() {
    return gnsdk_javaJNI.GnRating_ratingMPAA(swigCPtr, this);
  }

  public String ratingMPAATV() {
    return gnsdk_javaJNI.GnRating_ratingMPAATV(swigCPtr, this);
  }

  public String ratingFAB() {
    return gnsdk_javaJNI.GnRating_ratingFAB(swigCPtr, this);
  }

  public String ratingCHVRS() {
    return gnsdk_javaJNI.GnRating_ratingCHVRS(swigCPtr, this);
  }

  public String ratingCanadianTV() {
    return gnsdk_javaJNI.GnRating_ratingCanadianTV(swigCPtr, this);
  }

  public String ratingBBFC() {
    return gnsdk_javaJNI.GnRating_ratingBBFC(swigCPtr, this);
  }

  public String ratingCBFC() {
    return gnsdk_javaJNI.GnRating_ratingCBFC(swigCPtr, this);
  }

  public String ratingOFLC() {
    return gnsdk_javaJNI.GnRating_ratingOFLC(swigCPtr, this);
  }

  public String ratingHongKong() {
    return gnsdk_javaJNI.GnRating_ratingHongKong(swigCPtr, this);
  }

  public String ratingFinnish() {
    return gnsdk_javaJNI.GnRating_ratingFinnish(swigCPtr, this);
  }

  public String ratingKMRB() {
    return gnsdk_javaJNI.GnRating_ratingKMRB(swigCPtr, this);
  }

  public String ratingDVDParental() {
    return gnsdk_javaJNI.GnRating_ratingDVDParental(swigCPtr, this);
  }

  public String ratingEIRIN() {
    return gnsdk_javaJNI.GnRating_ratingEIRIN(swigCPtr, this);
  }

  public String ratingINCAA() {
    return gnsdk_javaJNI.GnRating_ratingINCAA(swigCPtr, this);
  }

  public String ratingDJTCQ() {
    return gnsdk_javaJNI.GnRating_ratingDJTCQ(swigCPtr, this);
  }

  public String ratingQuebec() {
    return gnsdk_javaJNI.GnRating_ratingQuebec(swigCPtr, this);
  }

  public String ratingFrance() {
    return gnsdk_javaJNI.GnRating_ratingFrance(swigCPtr, this);
  }

  public String ratingFSK() {
    return gnsdk_javaJNI.GnRating_ratingFSK(swigCPtr, this);
  }

  public String ratingItaly() {
    return gnsdk_javaJNI.GnRating_ratingItaly(swigCPtr, this);
  }

  public String ratingSpain() {
    return gnsdk_javaJNI.GnRating_ratingSpain(swigCPtr, this);
  }

}
