/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnResponseTracks extends GnDataObject {
  private long swigCPtr;

  protected GnResponseTracks(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnResponseTracks_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnResponseTracks obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnResponseTracks(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnResponseTracks_gnType();
  }

  public static GnResponseTracks from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnResponseTracks(gnsdk_javaJNI.GnResponseTracks_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long resultCount() {
    return gnsdk_javaJNI.GnResponseTracks_resultCount(swigCPtr, this);
  }

  public long rangeStart() {
    return gnsdk_javaJNI.GnResponseTracks_rangeStart(swigCPtr, this);
  }

  public long rangeEnd() {
    return gnsdk_javaJNI.GnResponseTracks_rangeEnd(swigCPtr, this);
  }

  public long rangeTotal() {
    return gnsdk_javaJNI.GnResponseTracks_rangeTotal(swigCPtr, this);
  }

  public boolean needsDecision() {
    return gnsdk_javaJNI.GnResponseTracks_needsDecision(swigCPtr, this);
  }

  public GnTrackIterable tracks() {
    return new GnTrackIterable(gnsdk_javaJNI.GnResponseTracks_tracks(swigCPtr, this), true);
  }

}
