/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnResponseVideoSuggestions extends GnDataObject {
  private long swigCPtr;

  protected GnResponseVideoSuggestions(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnResponseVideoSuggestions_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnResponseVideoSuggestions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnResponseVideoSuggestions(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_gnType();
  }

  public static GnResponseVideoSuggestions from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnResponseVideoSuggestions(gnsdk_javaJNI.GnResponseVideoSuggestions_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long resultCount() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_resultCount(swigCPtr, this);
  }

  public long rangeStart() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_rangeStart(swigCPtr, this);
  }

  public long rangeEnd() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_rangeEnd(swigCPtr, this);
  }

  public long rangeTotal() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_rangeTotal(swigCPtr, this);
  }

  public boolean needsDecision() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_needsDecision(swigCPtr, this);
  }

  public String suggestionText() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_suggestionText(swigCPtr, this);
  }

  public String suggestionTitle(long ordinal) {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_suggestionTitle(swigCPtr, this, ordinal);
  }

  public String suggestionType() {
    return gnsdk_javaJNI.GnResponseVideoSuggestions_suggestionType(swigCPtr, this);
  }

}
