/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnResponseVideoSeries extends GnDataObject {
  private long swigCPtr;

  protected GnResponseVideoSeries(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnResponseVideoSeries_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnResponseVideoSeries obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnResponseVideoSeries(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnResponseVideoSeries_gnType();
  }

  public static GnResponseVideoSeries from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnResponseVideoSeries(gnsdk_javaJNI.GnResponseVideoSeries_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long resultCount() {
    return gnsdk_javaJNI.GnResponseVideoSeries_resultCount(swigCPtr, this);
  }

  public long rangeStart() {
    return gnsdk_javaJNI.GnResponseVideoSeries_rangeStart(swigCPtr, this);
  }

  public long rangeEnd() {
    return gnsdk_javaJNI.GnResponseVideoSeries_rangeEnd(swigCPtr, this);
  }

  public long rangeTotal() {
    return gnsdk_javaJNI.GnResponseVideoSeries_rangeTotal(swigCPtr, this);
  }

  public boolean needsDecision() {
    return gnsdk_javaJNI.GnResponseVideoSeries_needsDecision(swigCPtr, this);
  }

  public GnVideoSeriesIterable series() {
    return new GnVideoSeriesIterable(gnsdk_javaJNI.GnResponseVideoSeries_series(swigCPtr, this), true);
  }

}
