/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnResponseVideoProduct extends GnDataObject {
  private long swigCPtr;

  protected GnResponseVideoProduct(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnResponseVideoProduct_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnResponseVideoProduct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnResponseVideoProduct(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnResponseVideoProduct_gnType();
  }

  public static GnResponseVideoProduct from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnResponseVideoProduct(gnsdk_javaJNI.GnResponseVideoProduct_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long resultCount() {
    return gnsdk_javaJNI.GnResponseVideoProduct_resultCount(swigCPtr, this);
  }

  public long rangeStart() {
    return gnsdk_javaJNI.GnResponseVideoProduct_rangeStart(swigCPtr, this);
  }

  public long rangeEnd() {
    return gnsdk_javaJNI.GnResponseVideoProduct_rangeEnd(swigCPtr, this);
  }

  public long rangeTotal() {
    return gnsdk_javaJNI.GnResponseVideoProduct_rangeTotal(swigCPtr, this);
  }

  public boolean needsDecision() {
    return gnsdk_javaJNI.GnResponseVideoProduct_needsDecision(swigCPtr, this);
  }

  public GnVideoProductIterable products() {
    return new GnVideoProductIterable(gnsdk_javaJNI.GnResponseVideoProduct_products(swigCPtr, this), true);
  }

}
