/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnRole extends GnDataObject {
  private long swigCPtr;

  protected GnRole(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnRole_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnRole obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnRole(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public String category() {
    return gnsdk_javaJNI.GnRole_category(swigCPtr, this);
  }

  public String role() {
    return gnsdk_javaJNI.GnRole_role(swigCPtr, this);
  }

}
