/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public enum GnStatus {
  kStatusUnknown(0),
  kStatusBegin,
  kStatusProgress,
  kStatusComplete,
  kStatusErrorInfo,
  kStatusConnecting,
  kStatusSending,
  kStatusReceiving,
  kStatusDisconnected,
  kStatusReading,
  kStatusWriting,
  kStatusCancelled;

  protected final int swigValue() {
    return swigValue;
  }

  protected static GnStatus swigToEnum(int swigValue) {
    GnStatus[] swigValues = GnStatus.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (GnStatus swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + GnStatus.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private GnStatus() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private GnStatus(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private GnStatus(GnStatus swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

