/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTitle extends GnDataObject {
  private long swigCPtr;

  protected GnTitle(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnTitle_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTitle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTitle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnTitle_gnType();
  }

  public static GnTitle from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnTitle(gnsdk_javaJNI.GnTitle_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public String language() {
    return gnsdk_javaJNI.GnTitle_language(swigCPtr, this);
  }

  public String languageCode() {
    return gnsdk_javaJNI.GnTitle_languageCode(swigCPtr, this);
  }

  public String display() {
    return gnsdk_javaJNI.GnTitle_display(swigCPtr, this);
  }

  public String prefix() {
    return gnsdk_javaJNI.GnTitle_prefix(swigCPtr, this);
  }

  public String sortable() {
    return gnsdk_javaJNI.GnTitle_sortable(swigCPtr, this);
  }

  public String sortableScheme() {
    return gnsdk_javaJNI.GnTitle_sortableScheme(swigCPtr, this);
  }

  public String mainTitle() {
    return gnsdk_javaJNI.GnTitle_mainTitle(swigCPtr, this);
  }

  public String edition() {
    return gnsdk_javaJNI.GnTitle_edition(swigCPtr, this);
  }

}
