/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnTrack extends GnDataObject {
  private long swigCPtr;

  protected GnTrack(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnTrack_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnTrack obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnTrack(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnTrack_gnType();
  }

  public static GnTrack from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnTrack(gnsdk_javaJNI.GnTrack_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public GnTrack(String id, String idTag) throws com.gracenote.gnsdk.GnException {
    this(gnsdk_javaJNI.new_GnTrack(id, idTag), true);
  }

  public boolean isFullResult() {
    return gnsdk_javaJNI.GnTrack_isFullResult(swigCPtr, this);
  }

  public GnTitle title() {
    return new GnTitle(gnsdk_javaJNI.GnTrack_title(swigCPtr, this), true);
  }

  public GnArtist artist() {
    return new GnArtist(gnsdk_javaJNI.GnTrack_artist(swigCPtr, this), true);
  }

  public GnAudioWork work() {
    return new GnAudioWork(gnsdk_javaJNI.GnTrack_work(swigCPtr, this), true);
  }

  public String mood(GnDataLevel level) {
    return gnsdk_javaJNI.GnTrack_mood(swigCPtr, this, level.swigValue());
  }

  public String tempo(GnDataLevel level) {
    return gnsdk_javaJNI.GnTrack_tempo(swigCPtr, this, level.swigValue());
  }

  public String genre(GnDataLevel level) {
    return gnsdk_javaJNI.GnTrack_genre(swigCPtr, this, level.swigValue());
  }

  public GnContent content(GnContentType contentType) {
    return new GnContent(gnsdk_javaJNI.GnTrack_content(swigCPtr, this, contentType.swigValue()), true);
  }

  public GnContent review() {
    return new GnContent(gnsdk_javaJNI.GnTrack_review(swigCPtr, this), true);
  }

  public boolean matched() {
    return gnsdk_javaJNI.GnTrack_matched(swigCPtr, this);
  }

  public long matchPosition() {
    return gnsdk_javaJNI.GnTrack_matchPosition(swigCPtr, this);
  }

  public long matchDuration() {
    return gnsdk_javaJNI.GnTrack_matchDuration(swigCPtr, this);
  }

  public long currentPosition() {
    return gnsdk_javaJNI.GnTrack_currentPosition(swigCPtr, this);
  }

  public long duration() {
    return gnsdk_javaJNI.GnTrack_duration(swigCPtr, this);
  }

  public GnCreditIterable credits() {
    return new GnCreditIterable(gnsdk_javaJNI.GnTrack_credits(swigCPtr, this), true);
  }

  public GnContentIterable contents() {
    return new GnContentIterable(gnsdk_javaJNI.GnTrack_contents(swigCPtr, this), true);
  }

  public GnExternalIdIterable externalIds() {
    return new GnExternalIdIterable(gnsdk_javaJNI.GnTrack_externalIds(swigCPtr, this), true);
  }

  public String tui() {
    return gnsdk_javaJNI.GnTrack_tui(swigCPtr, this);
  }

  public String tuiTag() {
    return gnsdk_javaJNI.GnTrack_tuiTag(swigCPtr, this);
  }

  public String tagId() {
    return gnsdk_javaJNI.GnTrack_tagId(swigCPtr, this);
  }

  public String gnId() {
    return gnsdk_javaJNI.GnTrack_gnId(swigCPtr, this);
  }

  public String gnUId() {
    return gnsdk_javaJNI.GnTrack_gnUId(swigCPtr, this);
  }

  public String trackNumber() {
    return gnsdk_javaJNI.GnTrack_trackNumber(swigCPtr, this);
  }

  public String year() {
    return gnsdk_javaJNI.GnTrack_year(swigCPtr, this);
  }

  public GnStringValueIterable matchedIdents() {
    return new GnStringValueIterable(gnsdk_javaJNI.GnTrack_matchedIdents(swigCPtr, this), true);
  }

  public String matchLookupType() {
    return gnsdk_javaJNI.GnTrack_matchLookupType(swigCPtr, this);
  }

  public String matchConfidence() {
    return gnsdk_javaJNI.GnTrack_matchConfidence(swigCPtr, this);
  }

  public long matchScore() {
    return gnsdk_javaJNI.GnTrack_matchScore(swigCPtr, this);
  }

  public GnTitle titleClassical() {
    return new GnTitle(gnsdk_javaJNI.GnTrack_titleClassical(swigCPtr, this), true);
  }

  public GnTitle titleRegional() {
    return new GnTitle(gnsdk_javaJNI.GnTrack_titleRegional(swigCPtr, this), true);
  }

}
