/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoLayerIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoLayerIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoLayerIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoLayerIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoLayer __ref__() throws com.gracenote.gnsdk.GnException {
    return new GnVideoLayer(gnsdk_javaJNI.GnVideoLayerIterator___ref__(swigCPtr, this), false);
  }

  public GnVideoLayer next() throws com.gracenote.gnsdk.GnException {
    return new GnVideoLayer(gnsdk_javaJNI.GnVideoLayerIterator_next(swigCPtr, this), true);
  }

  public boolean hasNext() {
    return gnsdk_javaJNI.GnVideoLayerIterator_hasNext(swigCPtr, this);
  }

  public long distance(GnVideoLayerIterator itr) {
    return gnsdk_javaJNI.GnVideoLayerIterator_distance(swigCPtr, this, GnVideoLayerIterator.getCPtr(itr), itr);
  }

  public GnVideoLayerIterator(GnVideoLayerProvider provider, long pos) {
    this(gnsdk_javaJNI.new_GnVideoLayerIterator(GnVideoLayerProvider.getCPtr(provider), provider, pos), true);
  }

}
