/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoSeasonIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoSeasonIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoSeasonIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoSeasonIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoSeasonIterable(GnVideoSeasonProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnVideoSeasonIterable(GnVideoSeasonProvider.getCPtr(provider), provider, start), true);
  }

  public GnVideoSeasonIterator getIterator() {
    return new GnVideoSeasonIterator(gnsdk_javaJNI.GnVideoSeasonIterable_getIterator(swigCPtr, this), true);
  }

  public GnVideoSeasonIterator end() {
    return new GnVideoSeasonIterator(gnsdk_javaJNI.GnVideoSeasonIterable_end(swigCPtr, this), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnVideoSeasonIterable_count(swigCPtr, this);
  }

  public GnVideoSeasonIterator at(long index) {
    return new GnVideoSeasonIterator(gnsdk_javaJNI.GnVideoSeasonIterable_at(swigCPtr, this, index), true);
  }

  public GnVideoSeasonIterator getByIndex(long index) {
    return new GnVideoSeasonIterator(gnsdk_javaJNI.GnVideoSeasonIterable_getByIndex(swigCPtr, this, index), true);
  }

}
