/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoDiscIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoDiscIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoDiscIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoDiscIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoDiscIterable(GnVideoDiscProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnVideoDiscIterable(GnVideoDiscProvider.getCPtr(provider), provider, start), true);
  }

  public GnVideoDiscIterator getIterator() {
    return new GnVideoDiscIterator(gnsdk_javaJNI.GnVideoDiscIterable_getIterator(swigCPtr, this), true);
  }

  public GnVideoDiscIterator end() {
    return new GnVideoDiscIterator(gnsdk_javaJNI.GnVideoDiscIterable_end(swigCPtr, this), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnVideoDiscIterable_count(swigCPtr, this);
  }

  public GnVideoDiscIterator at(long index) {
    return new GnVideoDiscIterator(gnsdk_javaJNI.GnVideoDiscIterable_at(swigCPtr, this, index), true);
  }

  public GnVideoDiscIterator getByIndex(long index) {
    return new GnVideoDiscIterator(gnsdk_javaJNI.GnVideoDiscIterable_getByIndex(swigCPtr, this, index), true);
  }

}
