/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoProduct extends GnDataObject {
  private long swigCPtr;

  protected GnVideoProduct(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnVideoProduct_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoProduct obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoProduct(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnVideoProduct_gnType();
  }

  public static GnVideoProduct from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnVideoProduct(gnsdk_javaJNI.GnVideoProduct_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public GnVideoProduct(String id, String idTag) throws com.gracenote.gnsdk.GnException {
    this(gnsdk_javaJNI.new_GnVideoProduct(id, idTag), true);
  }

  public boolean isFullResult() {
    return gnsdk_javaJNI.GnVideoProduct_isFullResult(swigCPtr, this);
  }

  public String gnId() {
    return gnsdk_javaJNI.GnVideoProduct_gnId(swigCPtr, this);
  }

  public String gnUId() {
    return gnsdk_javaJNI.GnVideoProduct_gnUId(swigCPtr, this);
  }

  public String productId() {
    return gnsdk_javaJNI.GnVideoProduct_productId(swigCPtr, this);
  }

  public String tui() {
    return gnsdk_javaJNI.GnVideoProduct_tui(swigCPtr, this);
  }

  public String tuiTag() {
    return gnsdk_javaJNI.GnVideoProduct_tuiTag(swigCPtr, this);
  }

  public String packageLanguageDisplay() {
    return gnsdk_javaJNI.GnVideoProduct_packageLanguageDisplay(swigCPtr, this);
  }

  public String packageLanguage() {
    return gnsdk_javaJNI.GnVideoProduct_packageLanguage(swigCPtr, this);
  }

  public String videoProductionType() {
    return gnsdk_javaJNI.GnVideoProduct_videoProductionType(swigCPtr, this);
  }

  public long videoProductionTypeId() {
    return gnsdk_javaJNI.GnVideoProduct_videoProductionTypeId(swigCPtr, this);
  }

  public String dateOriginalRelease() {
    return gnsdk_javaJNI.GnVideoProduct_dateOriginalRelease(swigCPtr, this);
  }

  public String dateRelease() {
    return gnsdk_javaJNI.GnVideoProduct_dateRelease(swigCPtr, this);
  }

  public long duration() {
    return gnsdk_javaJNI.GnVideoProduct_duration(swigCPtr, this);
  }

  public String durationUnits() {
    return gnsdk_javaJNI.GnVideoProduct_durationUnits(swigCPtr, this);
  }

  public String aspectRatio() {
    return gnsdk_javaJNI.GnVideoProduct_aspectRatio(swigCPtr, this);
  }

  public String aspectRatioType() {
    return gnsdk_javaJNI.GnVideoProduct_aspectRatioType(swigCPtr, this);
  }

  public String videoRegion() {
    return gnsdk_javaJNI.GnVideoProduct_videoRegion(swigCPtr, this);
  }

  public String videoRegionDesc() {
    return gnsdk_javaJNI.GnVideoProduct_videoRegionDesc(swigCPtr, this);
  }

  public String notes() {
    return gnsdk_javaJNI.GnVideoProduct_notes(swigCPtr, this);
  }

  public String commerceType() {
    return gnsdk_javaJNI.GnVideoProduct_commerceType(swigCPtr, this);
  }

  public String genre(GnDataLevel level) {
    return gnsdk_javaJNI.GnVideoProduct_genre(swigCPtr, this, level.swigValue());
  }

  public GnRating rating() {
    return new GnRating(gnsdk_javaJNI.GnVideoProduct_rating(swigCPtr, this), true);
  }

  public GnTitle officialTitle() {
    return new GnTitle(gnsdk_javaJNI.GnVideoProduct_officialTitle(swigCPtr, this), true);
  }

  public GnExternalIdIterable externalIds() {
    return new GnExternalIdIterable(gnsdk_javaJNI.GnVideoProduct_externalIds(swigCPtr, this), true);
  }

  public GnVideoDiscIterable discs() {
    return new GnVideoDiscIterable(gnsdk_javaJNI.GnVideoProduct_discs(swigCPtr, this), true);
  }

  public GnContentIterable contents() {
    return new GnContentIterable(gnsdk_javaJNI.GnVideoProduct_contents(swigCPtr, this), true);
  }

}
