/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoWorkIterable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GnVideoWorkIterable(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoWorkIterable obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoWorkIterable(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnVideoWorkIterable(GnVideoWorkProvider provider, long start) {
    this(gnsdk_javaJNI.new_GnVideoWorkIterable(GnVideoWorkProvider.getCPtr(provider), provider, start), true);
  }

  public GnVideoWorkIterator getIterator() {
    return new GnVideoWorkIterator(gnsdk_javaJNI.GnVideoWorkIterable_getIterator(swigCPtr, this), true);
  }

  public GnVideoWorkIterator end() {
    return new GnVideoWorkIterator(gnsdk_javaJNI.GnVideoWorkIterable_end(swigCPtr, this), true);
  }

  public long count() {
    return gnsdk_javaJNI.GnVideoWorkIterable_count(swigCPtr, this);
  }

  public GnVideoWorkIterator at(long index) {
    return new GnVideoWorkIterator(gnsdk_javaJNI.GnVideoWorkIterable_at(swigCPtr, this, index), true);
  }

  public GnVideoWorkIterator getByIndex(long index) {
    return new GnVideoWorkIterator(gnsdk_javaJNI.GnVideoWorkIterable_getByIndex(swigCPtr, this, index), true);
  }

}
