/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoFeature extends GnDataObject {
  private long swigCPtr;

  protected GnVideoFeature(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnVideoFeature_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoFeature obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoFeature(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnVideoFeature_gnType();
  }

  public static GnVideoFeature from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnVideoFeature(gnsdk_javaJNI.GnVideoFeature_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long ordinal() {
    return gnsdk_javaJNI.GnVideoFeature_ordinal(swigCPtr, this);
  }

  public boolean matched() {
    return gnsdk_javaJNI.GnVideoFeature_matched(swigCPtr, this);
  }

  public String videoFeatureType() {
    return gnsdk_javaJNI.GnVideoFeature_videoFeatureType(swigCPtr, this);
  }

  public String videoProductionType() {
    return gnsdk_javaJNI.GnVideoFeature_videoProductionType(swigCPtr, this);
  }

  public long videoProductionTypeId() {
    return gnsdk_javaJNI.GnVideoFeature_videoProductionTypeId(swigCPtr, this);
  }

  public String dateRelease() {
    return gnsdk_javaJNI.GnVideoFeature_dateRelease(swigCPtr, this);
  }

  public String dateOriginalRelease() {
    return gnsdk_javaJNI.GnVideoFeature_dateOriginalRelease(swigCPtr, this);
  }

  public String notes() {
    return gnsdk_javaJNI.GnVideoFeature_notes(swigCPtr, this);
  }

  public String aspectRatio() {
    return gnsdk_javaJNI.GnVideoFeature_aspectRatio(swigCPtr, this);
  }

  public String aspectRatioType() {
    return gnsdk_javaJNI.GnVideoFeature_aspectRatioType(swigCPtr, this);
  }

  public long duration() {
    return gnsdk_javaJNI.GnVideoFeature_duration(swigCPtr, this);
  }

  public String durationUnits() {
    return gnsdk_javaJNI.GnVideoFeature_durationUnits(swigCPtr, this);
  }

  public String plotSummary() {
    return gnsdk_javaJNI.GnVideoFeature_plotSummary(swigCPtr, this);
  }

  public String plotSynopsis() {
    return gnsdk_javaJNI.GnVideoFeature_plotSynopsis(swigCPtr, this);
  }

  public String plotTagline() {
    return gnsdk_javaJNI.GnVideoFeature_plotTagline(swigCPtr, this);
  }

  public String plotSynopsisLanguage() {
    return gnsdk_javaJNI.GnVideoFeature_plotSynopsisLanguage(swigCPtr, this);
  }

  public String genre(GnDataLevel level) {
    return gnsdk_javaJNI.GnVideoFeature_genre(swigCPtr, this, level.swigValue());
  }

  public GnTitle officialTitle() {
    return new GnTitle(gnsdk_javaJNI.GnVideoFeature_officialTitle(swigCPtr, this), true);
  }

  public GnRating rating() {
    return new GnRating(gnsdk_javaJNI.GnVideoFeature_rating(swigCPtr, this), true);
  }

  public GnVideoWorkIterable works() {
    return new GnVideoWorkIterable(gnsdk_javaJNI.GnVideoFeature_works(swigCPtr, this), true);
  }

  public GnVideoChapterIterable chapters() {
    return new GnVideoChapterIterable(gnsdk_javaJNI.GnVideoFeature_chapters(swigCPtr, this), true);
  }

  public GnVideoCreditIterable videoCredits() {
    return new GnVideoCreditIterable(gnsdk_javaJNI.GnVideoFeature_videoCredits(swigCPtr, this), true);
  }

}
