/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class GnVideoLayer extends GnDataObject {
  private long swigCPtr;

  protected GnVideoLayer(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.GnVideoLayer_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GnVideoLayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_GnVideoLayer(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static String gnType() {
    return gnsdk_javaJNI.GnVideoLayer_gnType();
  }

  public static GnVideoLayer from(GnDataObject obj) throws com.gracenote.gnsdk.GnException {
    return new GnVideoLayer(gnsdk_javaJNI.GnVideoLayer_from(GnDataObject.getCPtr(obj), obj), true);
  }

  public long ordinal() {
    return gnsdk_javaJNI.GnVideoLayer_ordinal(swigCPtr, this);
  }

  public boolean matched() {
    return gnsdk_javaJNI.GnVideoLayer_matched(swigCPtr, this);
  }

  public String aspectRatio() {
    return gnsdk_javaJNI.GnVideoLayer_aspectRatio(swigCPtr, this);
  }

  public String aspectRatioType() {
    return gnsdk_javaJNI.GnVideoLayer_aspectRatioType(swigCPtr, this);
  }

  public String tvSystem() {
    return gnsdk_javaJNI.GnVideoLayer_tvSystem(swigCPtr, this);
  }

  public String regionCode() {
    return gnsdk_javaJNI.GnVideoLayer_regionCode(swigCPtr, this);
  }

  public String videoRegion() {
    return gnsdk_javaJNI.GnVideoLayer_videoRegion(swigCPtr, this);
  }

  public String videoRegionDesc() {
    return gnsdk_javaJNI.GnVideoLayer_videoRegionDesc(swigCPtr, this);
  }

  public String mediaType() {
    return gnsdk_javaJNI.GnVideoLayer_mediaType(swigCPtr, this);
  }

  public GnVideoFeatureIterable features() {
    return new GnVideoFeatureIterable(gnsdk_javaJNI.GnVideoLayer_features(swigCPtr, this), true);
  }

}
