/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

class IGnAudioSourceProxyL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IGnAudioSourceProxyL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGnAudioSourceProxyL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_IGnAudioSourceProxyL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  protected void swigReleaseOwnership() {
    swigCMemOwn = false;
    gnsdk_javaJNI.IGnAudioSourceProxyL_change_ownership(this, swigCPtr, false);
  }

  protected void swigTakeOwnership() {
    swigCMemOwn = true;
    gnsdk_javaJNI.IGnAudioSourceProxyL_change_ownership(this, swigCPtr, true);
  }

    private long getCancellerCPtrFromCancellable(IGnCancellable cancellable) {
    	if ( cancellable instanceof IGnCancellableProxy ){
    		IGnCancellableProxy canceller = (IGnCancellableProxy)cancellable;
    		return IGnCancellableProxy.getCPtr(canceller);
    	}
    	return 0;
    }

  public long sourceInit() {
    return gnsdk_javaJNI.IGnAudioSourceProxyL_sourceInit(swigCPtr, this);
  }

  public void sourceClose() {
    gnsdk_javaJNI.IGnAudioSourceProxyL_sourceClose(swigCPtr, this);
  }

  public long samplesPerSecond() {
    return gnsdk_javaJNI.IGnAudioSourceProxyL_samplesPerSecond(swigCPtr, this);
  }

  public long sampleSizeInBits() {
    return gnsdk_javaJNI.IGnAudioSourceProxyL_sampleSizeInBits(swigCPtr, this);
  }

  public long numberOfChannels() {
    return gnsdk_javaJNI.IGnAudioSourceProxyL_numberOfChannels(swigCPtr, this);
  }

  public long getData(java.nio.ByteBuffer dataBuffer, long dataSize) {
    return gnsdk_javaJNI.IGnAudioSourceProxyL_getData(swigCPtr, this, dataBuffer, dataSize);
  }

  public IGnAudioSourceProxyL() {
    this(gnsdk_javaJNI.new_IGnAudioSourceProxyL(), true);
    gnsdk_javaJNI.IGnAudioSourceProxyL_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
