/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

class IGnLogEventsProxyL {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IGnLogEventsProxyL(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGnLogEventsProxyL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_IGnLogEventsProxyL(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  protected void swigReleaseOwnership() {
    swigCMemOwn = false;
    gnsdk_javaJNI.IGnLogEventsProxyL_change_ownership(this, swigCPtr, false);
  }

  protected void swigTakeOwnership() {
    swigCMemOwn = true;
    gnsdk_javaJNI.IGnLogEventsProxyL_change_ownership(this, swigCPtr, true);
  }

    private long getCancellerCPtrFromCancellable(IGnCancellable cancellable) {
    	if ( cancellable instanceof IGnCancellableProxy ){
    		IGnCancellableProxy canceller = (IGnCancellableProxy)cancellable;
    		return IGnCancellableProxy.getCPtr(canceller);
    	}
    	return 0;
    }

  public boolean logMessage(int packageId, GnLogMessageType messageType, long errorCode, String message) {
    return gnsdk_javaJNI.IGnLogEventsProxyL_logMessage(swigCPtr, this, packageId, messageType.swigValue(), errorCode, message);
  }

  public IGnLogEventsProxyL() {
    this(gnsdk_javaJNI.new_IGnLogEventsProxyL(), true);
    gnsdk_javaJNI.IGnLogEventsProxyL_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
