/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

class IGnMusicIdStreamEventsProxyL extends IGnStatusEventsProxyL {
  private long swigCPtr;

  protected IGnMusicIdStreamEventsProxyL(long cPtr, boolean cMemoryOwn) {
    super(gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IGnMusicIdStreamEventsProxyL obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_IGnMusicIdStreamEventsProxyL(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  protected void swigReleaseOwnership() {
    swigCMemOwn = false;
    gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_change_ownership(this, swigCPtr, false);
  }

  protected void swigTakeOwnership() {
    swigCMemOwn = true;
    gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_change_ownership(this, swigCPtr, true);
  }

    private long getCancellerCPtrFromCancellable(IGnCancellable cancellable) {
    	if ( cancellable instanceof IGnCancellableProxy ){
    		IGnCancellableProxy canceller = (IGnCancellableProxy)cancellable;
    		return IGnCancellableProxy.getCPtr(canceller);
    	}
    	return 0;
    }

  public void musicIdStreamProcessingStatusEvent(GnMusicIdStreamProcessingStatus status, IGnCancellable canceller) {
IGnCancellableProxy iGnCanceller = (canceller instanceof IGnCancellableProxy)?(IGnCancellableProxy)canceller:null;
    {
      gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_musicIdStreamProcessingStatusEvent(swigCPtr, this, status.swigValue(), getCancellerCPtrFromCancellable(canceller), iGnCanceller);
    }
  }

  public void musicIdStreamIdentifyingStatusEvent(GnMusicIdStreamIdentifyingStatus status, IGnCancellable canceller) {
IGnCancellableProxy iGnCanceller = (canceller instanceof IGnCancellableProxy)?(IGnCancellableProxy)canceller:null;
    {
      gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_musicIdStreamIdentifyingStatusEvent(swigCPtr, this, status.swigValue(), getCancellerCPtrFromCancellable(canceller), iGnCanceller);
    }
  }

  public void musicIdStreamAlbumResult(GnResponseAlbums result, IGnCancellable canceller) {
IGnCancellableProxy iGnCanceller = (canceller instanceof IGnCancellableProxy)?(IGnCancellableProxy)canceller:null;
    {
      gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_musicIdStreamAlbumResult(swigCPtr, this, GnResponseAlbums.getCPtr(result), result, getCancellerCPtrFromCancellable(canceller), iGnCanceller);
    }
  }

  public void musicIdStreamIdentifyCompletedWithError(GnError completeError) {
    gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_musicIdStreamIdentifyCompletedWithError(swigCPtr, this, GnError.getCPtr(completeError), completeError);
  }

  public IGnMusicIdStreamEventsProxyL() {
    this(gnsdk_javaJNI.new_IGnMusicIdStreamEventsProxyL(), true);
    gnsdk_javaJNI.IGnMusicIdStreamEventsProxyL_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
