/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.gracenote.gnsdk;

public class moodgrid_provider {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected moodgrid_provider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(moodgrid_provider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        gnsdk_javaJNI.delete_moodgrid_provider(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GnMoodgridProvider getData(long pos) {
    return new GnMoodgridProvider(gnsdk_javaJNI.moodgrid_provider_getData(swigCPtr, this, pos), true);
  }

  public long count() {
    return gnsdk_javaJNI.moodgrid_provider_count(swigCPtr, this);
  }

  public moodgrid_provider() {
    this(gnsdk_javaJNI.new_moodgrid_provider(), true);
  }

}
